package gay.mountainspring.sswplus.datagen;

import java.util.concurrent.CompletableFuture;

import gay.mountainspring.sswplus.SSWPlus;
import gay.mountainspring.sswplus.block.SSWPBlocks;
import gay.mountainspring.sswplus.block.SSWPCauldronGroups;
import gay.mountainspring.sswplus.item.SSWPItems;
import gay.mountainspring.sswplus.tag.SSWPTags;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.minecraft.block.Blocks;
import net.minecraft.registry.RegistryWrapper.WrapperLookup;

public class SSWPLangGen {
	private SSWPLangGen() {}
	
	protected static final class USEnglish extends FabricLanguageProvider {
		protected USEnglish(FabricDataOutput dataOutput, CompletableFuture<WrapperLookup> registryLookup) {
			super(dataOutput, registryLookup);
		}
		
		@Override
		public void generateTranslations(WrapperLookup registryLookup, TranslationBuilder builder) {
			builder.add(SSWPBlocks.OAK_LOG_SLAB, "Oak Log Slab");
			builder.add(SSWPBlocks.OAK_LOG_STAIRS, "Oak Log Stairs");
			builder.add(SSWPBlocks.OAK_LOG_WALL, "Oak Log Wall");
			builder.add(SSWPBlocks.OAK_WOOD_SLAB, "Oak Wood Slab");
			builder.add(SSWPBlocks.OAK_WOOD_STAIRS, "Oak Wood Stairs");
			builder.add(SSWPBlocks.OAK_WOOD_WALL, "Oak Wood Wall");
			builder.add(SSWPBlocks.STRIPPED_OAK_LOG_SLAB, "Stripped Oak Log Slab");
			builder.add(SSWPBlocks.STRIPPED_OAK_LOG_STAIRS, "Stripped Oak Log Stairs");
			builder.add(SSWPBlocks.STRIPPED_OAK_LOG_WALL, "Stripped Oak Log Wall");
			builder.add(SSWPBlocks.STRIPPED_OAK_WOOD_SLAB, "Stripped Oak Wood Slab");
			builder.add(SSWPBlocks.STRIPPED_OAK_WOOD_STAIRS, "Stripped Oak Wood Stairs");
			builder.add(SSWPBlocks.STRIPPED_OAK_WOOD_WALL, "Stripped Oak Wood Wall");
			builder.add(SSWPBlocks.SPRUCE_LOG_SLAB, "Spruce Log Slab");
			builder.add(SSWPBlocks.SPRUCE_LOG_STAIRS, "Spruce Log Stairs");
			builder.add(SSWPBlocks.SPRUCE_LOG_WALL, "Spruce Log Wall");
			builder.add(SSWPBlocks.SPRUCE_WOOD_SLAB, "Spruce Wood Slab");
			builder.add(SSWPBlocks.SPRUCE_WOOD_STAIRS, "Spruce Wood Stairs");
			builder.add(SSWPBlocks.SPRUCE_WOOD_WALL, "Spruce Wood Wall");
			builder.add(SSWPBlocks.STRIPPED_SPRUCE_LOG_SLAB, "Stripped Spruce Log Slab");
			builder.add(SSWPBlocks.STRIPPED_SPRUCE_LOG_STAIRS, "Stripped Spruce Log Stairs");
			builder.add(SSWPBlocks.STRIPPED_SPRUCE_LOG_WALL, "Stripped Spruce Log Wall");
			builder.add(SSWPBlocks.STRIPPED_SPRUCE_WOOD_SLAB, "Stripped Spruce Wood Slab");
			builder.add(SSWPBlocks.STRIPPED_SPRUCE_WOOD_STAIRS, "Stripped Spruce Wood Stairs");
			builder.add(SSWPBlocks.STRIPPED_SPRUCE_WOOD_WALL, "Stripped Spruce Wood Wall");
			builder.add(SSWPBlocks.BIRCH_LOG_SLAB, "Birch Log Slab");
			builder.add(SSWPBlocks.BIRCH_LOG_STAIRS, "Birch Log Stairs");
			builder.add(SSWPBlocks.BIRCH_LOG_WALL, "Birch Log Wall");
			builder.add(SSWPBlocks.BIRCH_WOOD_SLAB, "Birch Wood Slab");
			builder.add(SSWPBlocks.BIRCH_WOOD_STAIRS, "Birch Wood Stairs");
			builder.add(SSWPBlocks.BIRCH_WOOD_WALL, "Birch Wood Wall");
			builder.add(SSWPBlocks.STRIPPED_BIRCH_LOG_SLAB, "Stripped Birch Log Slab");
			builder.add(SSWPBlocks.STRIPPED_BIRCH_LOG_STAIRS, "Stripped Birch Log Stairs");
			builder.add(SSWPBlocks.STRIPPED_BIRCH_LOG_WALL, "Stripped Birch Log Wall");
			builder.add(SSWPBlocks.STRIPPED_BIRCH_WOOD_SLAB, "Stripped Birch Wood Slab");
			builder.add(SSWPBlocks.STRIPPED_BIRCH_WOOD_STAIRS, "Stripped Birch Wood Stairs");
			builder.add(SSWPBlocks.STRIPPED_BIRCH_WOOD_WALL, "Stripped Birch Wood Wall");
			builder.add(SSWPBlocks.JUNGLE_LOG_SLAB, "Jungle Log Slab");
			builder.add(SSWPBlocks.JUNGLE_LOG_STAIRS, "Jungle Log Stairs");
			builder.add(SSWPBlocks.JUNGLE_LOG_WALL, "Jungle Log Wall");
			builder.add(SSWPBlocks.JUNGLE_WOOD_SLAB, "Jungle Wood Slab");
			builder.add(SSWPBlocks.JUNGLE_WOOD_STAIRS, "Jungle Wood Stairs");
			builder.add(SSWPBlocks.JUNGLE_WOOD_WALL, "Jungle Wood Wall");
			builder.add(SSWPBlocks.STRIPPED_JUNGLE_LOG_SLAB, "Stripped Jungle Log Slab");
			builder.add(SSWPBlocks.STRIPPED_JUNGLE_LOG_STAIRS, "Stripped Jungle Log Stairs");
			builder.add(SSWPBlocks.STRIPPED_JUNGLE_LOG_WALL, "Stripped Jungle Log Wall");
			builder.add(SSWPBlocks.STRIPPED_JUNGLE_WOOD_SLAB, "Stripped Jungle Wood Slab");
			builder.add(SSWPBlocks.STRIPPED_JUNGLE_WOOD_STAIRS, "Stripped Jungle Wood Stairs");
			builder.add(SSWPBlocks.STRIPPED_JUNGLE_WOOD_WALL, "Stripped Jungle Wood Wall");
			builder.add(SSWPBlocks.ACACIA_LOG_SLAB, "Acacia Log Slab");
			builder.add(SSWPBlocks.ACACIA_LOG_STAIRS, "Acacia Log Stairs");
			builder.add(SSWPBlocks.ACACIA_LOG_WALL, "Acacia Log Wall");
			builder.add(SSWPBlocks.ACACIA_WOOD_SLAB, "Acacia Wood Slab");
			builder.add(SSWPBlocks.ACACIA_WOOD_STAIRS, "Acacia Wood Stairs");
			builder.add(SSWPBlocks.ACACIA_WOOD_WALL, "Acacia Wood Wall");
			builder.add(SSWPBlocks.STRIPPED_ACACIA_LOG_SLAB, "Stripped Acacia Log Slab");
			builder.add(SSWPBlocks.STRIPPED_ACACIA_LOG_STAIRS, "Stripped Acacia Log Stairs");
			builder.add(SSWPBlocks.STRIPPED_ACACIA_LOG_WALL, "Stripped Acacia Log Wall");
			builder.add(SSWPBlocks.STRIPPED_ACACIA_WOOD_SLAB, "Stripped Acacia Wood Slab");
			builder.add(SSWPBlocks.STRIPPED_ACACIA_WOOD_STAIRS, "Stripped Acacia Wood Stairs");
			builder.add(SSWPBlocks.STRIPPED_ACACIA_WOOD_WALL, "Stripped Acacia Wood Wall");
			builder.add(SSWPBlocks.DARK_OAK_LOG_SLAB, "Dark Oak Log Slab");
			builder.add(SSWPBlocks.DARK_OAK_LOG_STAIRS, "Dark Oak Log Stairs");
			builder.add(SSWPBlocks.DARK_OAK_LOG_WALL, "Dark Oak Log Wall");
			builder.add(SSWPBlocks.DARK_OAK_WOOD_SLAB, "Dark Oak Wood Slab");
			builder.add(SSWPBlocks.DARK_OAK_WOOD_STAIRS, "Dark Oak Wood Stairs");
			builder.add(SSWPBlocks.DARK_OAK_WOOD_WALL, "Dark Oak Wood Wall");
			builder.add(SSWPBlocks.STRIPPED_DARK_OAK_LOG_SLAB, "Stripped Dark Oak Log Slab");
			builder.add(SSWPBlocks.STRIPPED_DARK_OAK_LOG_STAIRS, "Stripped Dark Oak Log Stairs");
			builder.add(SSWPBlocks.STRIPPED_DARK_OAK_LOG_WALL, "Stripped Dark Oak Log Wall");
			builder.add(SSWPBlocks.STRIPPED_DARK_OAK_WOOD_SLAB, "Stripped Dark Oak Wood Slab");
			builder.add(SSWPBlocks.STRIPPED_DARK_OAK_WOOD_STAIRS, "Stripped Dark Oak Wood Stairs");
			builder.add(SSWPBlocks.STRIPPED_DARK_OAK_WOOD_WALL, "Stripped Dark Oak Wood Wall");
			builder.add(SSWPBlocks.MANGROVE_LOG_SLAB, "Mangrove Log Slab");
			builder.add(SSWPBlocks.MANGROVE_LOG_STAIRS, "Mangrove Log Stairs");
			builder.add(SSWPBlocks.MANGROVE_LOG_WALL, "Mangrove Log Wall");
			builder.add(SSWPBlocks.MANGROVE_WOOD_SLAB, "Mangrove Wood Slab");
			builder.add(SSWPBlocks.MANGROVE_WOOD_STAIRS, "Mangrove Wood Stairs");
			builder.add(SSWPBlocks.MANGROVE_WOOD_WALL, "Mangrove Wood Wall");
			builder.add(SSWPBlocks.STRIPPED_MANGROVE_LOG_SLAB, "Stripped Mangrove Log Slab");
			builder.add(SSWPBlocks.STRIPPED_MANGROVE_LOG_STAIRS, "Stripped Mangrove Log Stairs");
			builder.add(SSWPBlocks.STRIPPED_MANGROVE_LOG_WALL, "Stripped Mangrove Log Wall");
			builder.add(SSWPBlocks.STRIPPED_MANGROVE_WOOD_SLAB, "Stripped Mangrove Wood Slab");
			builder.add(SSWPBlocks.STRIPPED_MANGROVE_WOOD_STAIRS, "Stripped Mangrove Wood Stairs");
			builder.add(SSWPBlocks.STRIPPED_MANGROVE_WOOD_WALL, "Stripped Mangrove Wood Wall");
			builder.add(SSWPBlocks.CHERRY_LOG_SLAB, "Cherry Log Slab");
			builder.add(SSWPBlocks.CHERRY_LOG_STAIRS, "Cherry Log Stairs");
			builder.add(SSWPBlocks.CHERRY_LOG_WALL, "Cherry Log Wall");
			builder.add(SSWPBlocks.CHERRY_WOOD_SLAB, "Cherry Wood Slab");
			builder.add(SSWPBlocks.CHERRY_WOOD_STAIRS, "Cherry Wood Stairs");
			builder.add(SSWPBlocks.CHERRY_WOOD_WALL, "Cherry Wood Wall");
			builder.add(SSWPBlocks.STRIPPED_CHERRY_LOG_SLAB, "Stripped Cherry Log Slab");
			builder.add(SSWPBlocks.STRIPPED_CHERRY_LOG_STAIRS, "Stripped Cherry Log Stairs");
			builder.add(SSWPBlocks.STRIPPED_CHERRY_LOG_WALL, "Stripped Cherry Log Wall");
			builder.add(SSWPBlocks.STRIPPED_CHERRY_WOOD_SLAB, "Stripped Cherry Wood Slab");
			builder.add(SSWPBlocks.STRIPPED_CHERRY_WOOD_STAIRS, "Stripped Cherry Wood Stairs");
			builder.add(SSWPBlocks.STRIPPED_CHERRY_WOOD_WALL, "Stripped Cherry Wood Wall");
			builder.add(SSWPBlocks.BAMBOO_BLOCK_SLAB, "Bamboo Slab");
			builder.add(SSWPBlocks.BAMBOO_BLOCK_STAIRS, "Bamboo Stairs");
			builder.add(SSWPBlocks.BAMBOO_BLOCK_WALL, "Bamboo Wall");
			builder.add(SSWPBlocks.STRIPPED_BAMBOO_BLOCK_SLAB, "Stripped Bamboo Slab");
			builder.add(SSWPBlocks.STRIPPED_BAMBOO_BLOCK_STAIRS, "Stripped Bamboo Stairs");
			builder.add(SSWPBlocks.STRIPPED_BAMBOO_BLOCK_WALL, "Stripped Bamboo Wall");
			builder.add(SSWPBlocks.CRIMSON_STEM_SLAB, "Crimson Stem Slab");
			builder.add(SSWPBlocks.CRIMSON_STEM_STAIRS, "Crimson Stem Stairs");
			builder.add(SSWPBlocks.CRIMSON_STEM_WALL, "Crimson Stem Wall");
			builder.add(SSWPBlocks.CRIMSON_HYPHAE_SLAB, "Crimson Hyphae Slab");
			builder.add(SSWPBlocks.CRIMSON_HYPHAE_STAIRS, "Crimson Hyphae Stairs");
			builder.add(SSWPBlocks.CRIMSON_HYPHAE_WALL, "Crimson Hyphae Wall");
			builder.add(SSWPBlocks.STRIPPED_CRIMSON_STEM_SLAB, "Stripped Crimson Stem Slab");
			builder.add(SSWPBlocks.STRIPPED_CRIMSON_STEM_STAIRS, "Stripped Crimson Stem Stairs");
			builder.add(SSWPBlocks.STRIPPED_CRIMSON_STEM_WALL, "Stripped Crimson Stem Wall");
			builder.add(SSWPBlocks.STRIPPED_CRIMSON_HYPHAE_SLAB, "Stripped Crimson Hyphae Slab");
			builder.add(SSWPBlocks.STRIPPED_CRIMSON_HYPHAE_STAIRS, "Stripped Crimson Hyphae Stairs");
			builder.add(SSWPBlocks.STRIPPED_CRIMSON_HYPHAE_WALL, "Stripped Crimson Hyphae Wall");
			builder.add(SSWPBlocks.WARPED_STEM_SLAB, "Warped Stem Slab");
			builder.add(SSWPBlocks.WARPED_STEM_STAIRS, "Warped Stem Stairs");
			builder.add(SSWPBlocks.WARPED_STEM_WALL, "Warped Stem Wall");
			builder.add(SSWPBlocks.WARPED_HYPHAE_SLAB, "Warped Hyphae Slab");
			builder.add(SSWPBlocks.WARPED_HYPHAE_STAIRS, "Warped Hyphae Stairs");
			builder.add(SSWPBlocks.WARPED_HYPHAE_WALL, "Warped Hyphae Wall");
			builder.add(SSWPBlocks.STRIPPED_WARPED_STEM_SLAB, "Stripped Warped Stem Slab");
			builder.add(SSWPBlocks.STRIPPED_WARPED_STEM_STAIRS, "Stripped Warped Stem Stairs");
			builder.add(SSWPBlocks.STRIPPED_WARPED_STEM_WALL, "Stripped Warped Stem Wall");
			builder.add(SSWPBlocks.STRIPPED_WARPED_HYPHAE_SLAB, "Stripped Warped Hyphae Slab");
			builder.add(SSWPBlocks.STRIPPED_WARPED_HYPHAE_STAIRS, "Stripped Warped Hyphae Stairs");
			builder.add(SSWPBlocks.STRIPPED_WARPED_HYPHAE_WALL, "Stripped Warped Hyphae Wall");
			builder.add(SSWPBlocks.STONE_WALL, "Stone Wall");
			builder.add(SSWPBlocks.SMOOTH_STONE_STAIRS, "Smooth Stone Stairs");
			builder.add(SSWPBlocks.SMOOTH_STONE_WALL, "Smooth Stone Wall");
			builder.add(SSWPBlocks.CRACKED_STONE_BRICK_SLAB, "Cracked Stone Brick Slab");
			builder.add(SSWPBlocks.CRACKED_STONE_BRICK_STAIRS, "Cracked Stone Brick Stairs");
			builder.add(SSWPBlocks.CRACKED_STONE_BRICK_WALL, "Cracked Stone Brick Wall");
			builder.add(SSWPBlocks.CHISELED_STONE_BRICK_SLAB, "Chiseled Stone Brick Slab");
			builder.add(SSWPBlocks.CHISELED_STONE_BRICK_STAIRS, "Chiseled Stone Brick Stairs");
			builder.add(SSWPBlocks.CHISELED_STONE_BRICK_WALL, "Chiseled Stone Brick Wall");
			builder.add(SSWPBlocks.POLISHED_GRANITE_WALL, "Polished Granite Wall");
			builder.add(SSWPBlocks.POLISHED_DIORITE_WALL, "Polished Diorite Wall");
			builder.add(SSWPBlocks.POLISHED_ANDESITE_WALL, "Polished Andesite Wall");
			builder.add(SSWPBlocks.DEEPSLATE_SLAB, "Deepslate Slab");
			builder.add(SSWPBlocks.DEEPSLATE_STAIRS, "Deepslate Stairs");
			builder.add(SSWPBlocks.DEEPSLATE_WALL, "Deepslate Wall");
			builder.add(SSWPBlocks.CHISELED_DEEPSLATE_SLAB, "Chiseled Deepslate Slab");
			builder.add(SSWPBlocks.CHISELED_DEEPSLATE_STAIRS, "Chiseled Deepslate Stairs");
			builder.add(SSWPBlocks.CHISELED_DEEPSLATE_WALL, "Chiseled Deepslate Wall");
			builder.add(SSWPBlocks.CRACKED_DEEPSLATE_BRICK_SLAB, "Cracked Deepslate Brick Slab");
			builder.add(SSWPBlocks.CRACKED_DEEPSLATE_BRICK_STAIRS, "Cracked Deepslate Brick Stairs");
			builder.add(SSWPBlocks.CRACKED_DEEPSLATE_BRICK_WALL, "Cracked Deepslate Brick Wall");
			builder.add(SSWPBlocks.CRACKED_DEEPSLATE_TILE_SLAB, "Cracked Deepslate Tile Slab");
			builder.add(SSWPBlocks.CRACKED_DEEPSLATE_TILE_STAIRS, "Cracked Deepslate Tile Stairs");
			builder.add(SSWPBlocks.CRACKED_DEEPSLATE_TILE_WALL, "Cracked Deepslate Tile Wall");
			builder.add(SSWPBlocks.CHISELED_TUFF_SLAB, "Chiseled Tuff Slab");
			builder.add(SSWPBlocks.CHISELED_TUFF_STAIRS, "Chiseled Tuff Stairs");
			builder.add(SSWPBlocks.CHISELED_TUFF_WALL, "Chiseled Tuff Wall");
			builder.add(SSWPBlocks.CHISELED_TUFF_BRICK_SLAB, "Chiseled Tuff Brick Slab");
			builder.add(SSWPBlocks.CHISELED_TUFF_BRICK_STAIRS, "Chiseled Tuff Brick Stairs");
			builder.add(SSWPBlocks.CHISELED_TUFF_BRICK_WALL, "Chiseled Tuff Brick Wall");
			builder.add(SSWPBlocks.PACKED_MUD_SLAB, "Packed Mud Slab");
			builder.add(SSWPBlocks.PACKED_MUD_STAIRS, "Packed Mud Stairs");
			builder.add(SSWPBlocks.PACKED_MUD_WALL, "Packed Mud Wall");
			builder.add(SSWPBlocks.CHISELED_SANDSTONE_SLAB, "Chiseled Sandstone Slab");
			builder.add(SSWPBlocks.CHISELED_SANDSTONE_STAIRS, "Chiseled Sandstone Stairs");
			builder.add(SSWPBlocks.CHISELED_SANDSTONE_WALL, "Chiseled Sandstone Wall");
			builder.add(SSWPBlocks.SMOOTH_SANDSTONE_WALL, "Smooth Sandstone Wall");
			builder.add(SSWPBlocks.CUT_SANDSTONE_STAIRS, "Cut Sandstone Stairs");
			builder.add(SSWPBlocks.CUT_SANDSTONE_WALL, "Cut Sandstone Wall");
			builder.add(SSWPBlocks.CHISELED_RED_SANDSTONE_SLAB, "Chiseled Red Sandstone Slab");
			builder.add(SSWPBlocks.CHISELED_RED_SANDSTONE_STAIRS, "Chiseled Red Sandstone Stairs");
			builder.add(SSWPBlocks.CHISELED_RED_SANDSTONE_WALL, "Chiseled Red Sandstone Wall");
			builder.add(SSWPBlocks.SMOOTH_RED_SANDSTONE_WALL, "Smooth Red Sandstone Wall");
			builder.add(SSWPBlocks.CUT_RED_SANDSTONE_STAIRS, "Cut Red Sandstone Stairs");
			builder.add(SSWPBlocks.CUT_RED_SANDSTONE_WALL, "Cut Red Sandstone Wall");
			builder.add(SSWPBlocks.SEA_LANTERN_SLAB, "Sea Lantern Slab");
			builder.add(SSWPBlocks.SEA_LANTERN_STAIRS, "Sea Lantern Stairs");
			builder.add(SSWPBlocks.SEA_LANTERN_WALL, "Sea Lantern Wall");
			builder.add(SSWPBlocks.PRISMARINE_BRICK_WALL, "Prismarine Brick Wall");
			builder.add(SSWPBlocks.DARK_PRISMARINE_WALL, "Dark Prismarine Wall");
			builder.add(SSWPBlocks.NETHERRACK_SLAB, "Netherrack Slab");
			builder.add(SSWPBlocks.NETHERRACK_STAIRS, "Netherrack Stairs");
			builder.add(SSWPBlocks.NETHERRACK_WALL, "Netherrack Wall");
			builder.add(SSWPBlocks.NETHER_BRICK_FENCE_GATE, "Nether Brick Fence Gate");
			builder.add(SSWPBlocks.CRACKED_NETHER_BRICK_SLAB, "Cracked Nether Brick Slab");
			builder.add(SSWPBlocks.CRACKED_NETHER_BRICK_STAIRS, "Cracked Nether Brick Stairs");
			builder.add(SSWPBlocks.CRACKED_NETHER_BRICK_WALL, "Cracked Nether Brick Wall");
			builder.add(SSWPBlocks.CRACKED_NETHER_BRICK_FENCE, "Cracked Nether Brick Fence");
			builder.add(SSWPBlocks.CRACKED_NETHER_BRICK_FENCE_GATE, "Cracked Nether Brick Fence Gate");
			builder.add(SSWPBlocks.CHISELED_NETHER_BRICK_SLAB, "Chiseled Nether Brick Slab");
			builder.add(SSWPBlocks.CHISELED_NETHER_BRICK_STAIRS, "Chiseled Nether Brick Stairs");
			builder.add(SSWPBlocks.CHISELED_NETHER_BRICK_WALL, "Chiseled Nether Brick Wall");
			builder.add(SSWPBlocks.RED_NETHER_BRICK_FENCE, "Red Nether Brick Fence");
			builder.add(SSWPBlocks.RED_NETHER_BRICK_FENCE_GATE, "Red Nether Brick Fence Gate");
			builder.add(SSWPBlocks.BASALT_SLAB, "Basalt Slab");
			builder.add(SSWPBlocks.BASALT_STAIRS, "Basalt Stairs");
			builder.add(SSWPBlocks.BASALT_WALL, "Basalt Wall");
			builder.add(SSWPBlocks.SMOOTH_BASALT_SLAB, "Smooth Basalt Slab");
			builder.add(SSWPBlocks.SMOOTH_BASALT_STAIRS, "Smooth Basalt Stairs");
			builder.add(SSWPBlocks.SMOOTH_BASALT_WALL, "Smooth Basalt Wall");
			builder.add(SSWPBlocks.POLISHED_BASALT_SLAB, "Polished Basalt Slab");
			builder.add(SSWPBlocks.POLISHED_BASALT_STAIRS, "Polished Basalt Stairs");
			builder.add(SSWPBlocks.POLISHED_BASALT_WALL, "Polished Basalt Wall");
			builder.add(SSWPBlocks.GILDED_BLACKSTONE_SLAB, "Gilded Blackstone Slab");
			builder.add(SSWPBlocks.GILDED_BLACKSTONE_STAIRS, "Gilded Blackstone Stairs");
			builder.add(SSWPBlocks.GILDED_BLACKSTONE_WALL, "Gilded Blackstone Wall");
			builder.add(SSWPBlocks.CHISELED_POLISHED_BLACKSTONE_SLAB, "Chiseled Polished Blackstone Slab");
			builder.add(SSWPBlocks.CHISELED_POLISHED_BLACKSTONE_STAIRS, "Chiseled Polished Blackstone Stairs");
			builder.add(SSWPBlocks.CHISELED_POLISHED_BLACKSTONE_WALL, "Chiseled Polished Blackstone Wall");
			builder.add(SSWPBlocks.CRACKED_POLISHED_BLACKSTONE_BRICK_SLAB, "Cracked Polished Blackstone Brick Slab");
			builder.add(SSWPBlocks.CRACKED_POLISHED_BLACKSTONE_BRICK_STAIRS, "Cracked Polished Blackstone Brick Stairs");
			builder.add(SSWPBlocks.CRACKED_POLISHED_BLACKSTONE_BRICK_WALL, "Cracked Polished Blackstone Brick Wall");
			builder.add(SSWPBlocks.END_STONE_SLAB, "End Stone Slab");
			builder.add(SSWPBlocks.END_STONE_STAIRS, "End Stone Stairs");
			builder.add(SSWPBlocks.END_STONE_WALL, "End Stone Wall");
			builder.add(SSWPBlocks.PURPUR_WALL, "Purpur Wall");
			builder.add(SSWPBlocks.PURPUR_PILLAR_SLAB, "Purpur Pillar Slab");
			builder.add(SSWPBlocks.PURPUR_PILLAR_STAIRS, "Purpur Pillar Stairs");
			builder.add(SSWPBlocks.PURPUR_PILLAR_WALL, "Purpur Pillar Wall");
			builder.add(SSWPBlocks.COAL_SLAB, "Coal Slab");
			builder.add(SSWPBlocks.COAL_STAIRS, "Coal Stairs");
			builder.add(SSWPBlocks.COAL_WALL, "Coal Wall");
			builder.add(SSWPBlocks.IRON_SLAB, "Iron Slab");
			builder.add(SSWPBlocks.IRON_STAIRS, "Iron Stairs");
			builder.add(SSWPBlocks.IRON_WALL, "Iron Wall");
			builder.add(SSWPBlocks.IRON_FENCE, "Iron Fence");
			builder.add(SSWPBlocks.IRON_FENCE_GATE, "Iron Fence Gate");
			builder.add(SSWPBlocks.IRON_BUTTON, "Iron Button");
			builder.add(Blocks.CHAIN, "Iron Chain");
			builder.add(SSWPBlocks.GOLD_SLAB, "Gold Slab");
			builder.add(SSWPBlocks.GOLD_STAIRS, "Gold Stairs");
			builder.add(SSWPBlocks.GOLD_WALL, "Gold Wall");
			builder.add(SSWPBlocks.GOLD_FENCE, "Gold Fence");
			builder.add(SSWPBlocks.GOLD_FENCE_GATE, "Gold Fence Gate");
			builder.add(SSWPBlocks.GOLD_BARS, "Gold Bars");
			builder.add(SSWPBlocks.GOLD_DOOR, "Gold Door");
			builder.add(SSWPBlocks.GOLD_TRAPDOOR, "Gold Trapdoor");
			builder.add(SSWPBlocks.GOLD_BUTTON, "Gold Button");
			builder.add(SSWPBlocks.GOLD_CHAIN, "Gold Chain");
			builder.add(SSWPBlocks.REDSTONE_SLAB, "Redstone Slab");
			builder.add(SSWPBlocks.REDSTONE_STAIRS, "Redstone Stairs");
			builder.add(SSWPBlocks.REDSTONE_WALL, "Redstone Wall");
			builder.add(SSWPBlocks.EMERALD_SLAB, "Emerald Slab");
			builder.add(SSWPBlocks.EMERALD_STAIRS, "Emerald Stairs");
			builder.add(SSWPBlocks.EMERALD_WALL, "Emerald Wall");
			builder.add(SSWPBlocks.LAPIS_SLAB, "Lapis Lazuli Slab");
			builder.add(SSWPBlocks.LAPIS_STAIRS, "Lapis Lazuli Stairs");
			builder.add(SSWPBlocks.LAPIS_WALL, "Lapis Lazuli Wall");
			builder.add(SSWPBlocks.DIAMOND_SLAB, "Diamond Slab");
			builder.add(SSWPBlocks.DIAMOND_STAIRS, "Diamond Stairs");
			builder.add(SSWPBlocks.DIAMOND_WALL, "Diamond Wall");
			builder.add(SSWPBlocks.NETHERITE_SLAB, "Netherite Slab");
			builder.add(SSWPBlocks.NETHERITE_STAIRS, "Netherite Stairs");
			builder.add(SSWPBlocks.NETHERITE_WALL, "Netherite Wall");
			builder.add(SSWPBlocks.NETHERITE_FENCE, "Netherite Fence");
			builder.add(SSWPBlocks.NETHERITE_FENCE_GATE, "Netherite Fence Gate");
			builder.add(SSWPBlocks.NETHERITE_BARS, "Netherite Bars");
			builder.add(SSWPBlocks.NETHERITE_DOOR, "Netherite Door");
			builder.add(SSWPBlocks.NETHERITE_TRAPDOOR, "Netherite Trapdoor");
			builder.add(SSWPBlocks.NETHERITE_PRESSURE_PLATE, "Netherite Pressure Plate");
			builder.add(SSWPBlocks.NETHERITE_BUTTON, "Netherite Button");
			builder.add(SSWPBlocks.NETHERITE_CHAIN, "Netherite Chain");
			builder.add(SSWPBlocks.QUARTZ_WALL, "Quartz Wall");
			builder.add(SSWPBlocks.CHISELED_QUARTZ_SLAB, "Chiseled Quartz Slab");
			builder.add(SSWPBlocks.CHISELED_QUARTZ_STAIRS, "Chiseled Quartz Stairs");
			builder.add(SSWPBlocks.CHISELED_QUARTZ_WALL, "Chiseled Quartz Wall");
			builder.add(SSWPBlocks.QUARTZ_BRICK_SLAB, "Quartz Brick Slab");
			builder.add(SSWPBlocks.QUARTZ_BRICK_STAIRS, "Quartz Brick Stairs");
			builder.add(SSWPBlocks.QUARTZ_BRICK_WALL, "Quartz Brick Wall");
			builder.add(SSWPBlocks.QUARTZ_PILLAR_SLAB, "Quartz Pillar Slab");
			builder.add(SSWPBlocks.QUARTZ_PILLAR_STAIRS, "Quartz Pillar Stairs");
			builder.add(SSWPBlocks.QUARTZ_PILLAR_WALL, "Quartz Pillar Wall");
			builder.add(SSWPBlocks.SMOOTH_QUARTZ_WALL, "Smooth Quartz Wall");
			builder.add(SSWPBlocks.AMETHYST_SLAB, "Amethyst Slab");
			builder.add(SSWPBlocks.AMETHYST_STAIRS, "Amethyst Stairs");
			builder.add(SSWPBlocks.AMETHYST_WALL, "Amethyst Wall");
			builder.add(SSWPBlocks.COPPER_SLAB, "Copper Slab");
			builder.add(SSWPBlocks.COPPER_STAIRS, "Copper Stairs");
			builder.add(SSWPBlocks.COPPER_WALL, "Copper Wall");
			builder.add(SSWPBlocks.COPPER_FENCE, "Copper Fence");
			builder.add(SSWPBlocks.COPPER_FENCE_GATE, "Copper Fence Gate");
			builder.add(SSWPBlocks.COPPER_BARS, "Copper Bars");
			builder.add(SSWPBlocks.COPPER_PRESSURE_PLATE, "Copper Pressure Plate");
			builder.add(SSWPBlocks.COPPER_BUTTON, "Copper Button");
			builder.add(SSWPBlocks.COPPER_CHAIN, "Copper Chain");
			builder.add(SSWPBlocks.CHISELED_COPPER_SLAB, "Chiseled Copper Slab");
			builder.add(SSWPBlocks.CHISELED_COPPER_STAIRS, "Chiseled Copper Stairs");
			builder.add(SSWPBlocks.CHISELED_COPPER_WALL, "Chiseled Copper Wall");
			builder.add(SSWPBlocks.COPPER_GRATE_SLAB, "Copper Grate Slab");
			builder.add(SSWPBlocks.COPPER_GRATE_STAIRS, "Copper Grate Stairs");
			builder.add(SSWPBlocks.COPPER_GRATE_WALL, "Copper Grate Wall");
			builder.add(SSWPBlocks.CUT_COPPER_WALL, "Cut Copper Wall");
			builder.add(SSWPBlocks.EXPOSED_COPPER_SLAB, "Exposed Copper Slab");
			builder.add(SSWPBlocks.EXPOSED_COPPER_STAIRS, "Exposed Copper Stairs");
			builder.add(SSWPBlocks.EXPOSED_COPPER_WALL, "Exposed Copper Wall");
			builder.add(SSWPBlocks.EXPOSED_COPPER_FENCE, "Exposed Copper Fence");
			builder.add(SSWPBlocks.EXPOSED_COPPER_FENCE_GATE, "Exposed Copper Fence Gate");
			builder.add(SSWPBlocks.EXPOSED_COPPER_BARS, "Exposed Copper Bars");
			builder.add(SSWPBlocks.EXPOSED_COPPER_PRESSURE_PLATE, "Exposed Copper Pressure Plate");
			builder.add(SSWPBlocks.EXPOSED_COPPER_BUTTON, "Exposed Copper Button");
			builder.add(SSWPBlocks.EXPOSED_COPPER_CHAIN, "Exposed Copper Chain");
			builder.add(SSWPBlocks.EXPOSED_CHISELED_COPPER_SLAB, "Exposed Chiseled Copper Slab");
			builder.add(SSWPBlocks.EXPOSED_CHISELED_COPPER_STAIRS, "Exposed Chiseled Copper Stairs");
			builder.add(SSWPBlocks.EXPOSED_CHISELED_COPPER_WALL, "Exposed Chiseled Copper Wall");
			builder.add(SSWPBlocks.EXPOSED_COPPER_GRATE_SLAB, "Exposed Copper Grate Slab");
			builder.add(SSWPBlocks.EXPOSED_COPPER_GRATE_STAIRS, "Exposed Copper Grate Stairs");
			builder.add(SSWPBlocks.EXPOSED_COPPER_GRATE_WALL, "Exposed Copper Grate Wall");
			builder.add(SSWPBlocks.EXPOSED_CUT_COPPER_WALL, "Exposed Cut Copper Wall");
			builder.add(SSWPBlocks.WEATHERED_COPPER_SLAB, "Weathered Copper Slab");
			builder.add(SSWPBlocks.WEATHERED_COPPER_STAIRS, "Weathered Copper Stairs");
			builder.add(SSWPBlocks.WEATHERED_COPPER_WALL, "Weathered Copper Wall");
			builder.add(SSWPBlocks.WEATHERED_COPPER_FENCE, "Weathered Copper Fence");
			builder.add(SSWPBlocks.WEATHERED_COPPER_FENCE_GATE, "Weathered Copper Fence Gate");
			builder.add(SSWPBlocks.WEATHERED_COPPER_BARS, "Weathered Copper Bars");
			builder.add(SSWPBlocks.WEATHERED_COPPER_PRESSURE_PLATE, "Weathered Copper Pressure Plate");
			builder.add(SSWPBlocks.WEATHERED_COPPER_BUTTON, "Weathered Copper Button");
			builder.add(SSWPBlocks.WEATHERED_COPPER_CHAIN, "Weathered Copper Chain");
			builder.add(SSWPBlocks.WEATHERED_CHISELED_COPPER_SLAB, "Weathered Chiseled Copper Slab");
			builder.add(SSWPBlocks.WEATHERED_CHISELED_COPPER_STAIRS, "Weathered Chiseled Copper Stairs");
			builder.add(SSWPBlocks.WEATHERED_CHISELED_COPPER_WALL, "Weathered Chiseled Copper Wall");
			builder.add(SSWPBlocks.WEATHERED_COPPER_GRATE_SLAB, "Weathered Copper Grate Slab");
			builder.add(SSWPBlocks.WEATHERED_COPPER_GRATE_STAIRS, "Weathered Copper Grate Stairs");
			builder.add(SSWPBlocks.WEATHERED_COPPER_GRATE_WALL, "Weathered Copper Grate Wall");
			builder.add(SSWPBlocks.WEATHERED_CUT_COPPER_WALL, "Weathered Cut Copper Wall");
			builder.add(SSWPBlocks.OXIDIZED_COPPER_SLAB, "Oxidized Copper Slab");
			builder.add(SSWPBlocks.OXIDIZED_COPPER_STAIRS, "Oxidized Copper Stairs");
			builder.add(SSWPBlocks.OXIDIZED_COPPER_WALL, "Oxidized Copper Wall");
			builder.add(SSWPBlocks.OXIDIZED_COPPER_FENCE, "Oxidized Copper Fence");
			builder.add(SSWPBlocks.OXIDIZED_COPPER_FENCE_GATE, "Oxidized Copper Fence Gate");
			builder.add(SSWPBlocks.OXIDIZED_COPPER_BARS, "Oxidized Copper Bars");
			builder.add(SSWPBlocks.OXIDIZED_COPPER_PRESSURE_PLATE, "Oxidized Copper Pressure Plate");
			builder.add(SSWPBlocks.OXIDIZED_COPPER_BUTTON, "Oxidized Copper Button");
			builder.add(SSWPBlocks.OXIDIZED_COPPER_CHAIN, "Oxidized Copper Chain");
			builder.add(SSWPBlocks.OXIDIZED_CHISELED_COPPER_SLAB, "Oxidized Chiseled Copper Slab");
			builder.add(SSWPBlocks.OXIDIZED_CHISELED_COPPER_STAIRS, "Oxidized Chiseled Copper Stairs");
			builder.add(SSWPBlocks.OXIDIZED_CHISELED_COPPER_WALL, "Oxidized Chiseled Copper Wall");
			builder.add(SSWPBlocks.OXIDIZED_COPPER_GRATE_SLAB, "Oxidized Copper Grate Slab");
			builder.add(SSWPBlocks.OXIDIZED_COPPER_GRATE_STAIRS, "Oxidized Copper Grate Stairs");
			builder.add(SSWPBlocks.OXIDIZED_COPPER_GRATE_WALL, "Oxidized Copper Grate Wall");
			builder.add(SSWPBlocks.OXIDIZED_CUT_COPPER_WALL, "Oxidized Cut Copper Wall");
			builder.add(SSWPBlocks.WAXED_COPPER_SLAB, "Waxed Copper Slab");
			builder.add(SSWPBlocks.WAXED_COPPER_STAIRS, "Waxed Copper Stairs");
			builder.add(SSWPBlocks.WAXED_COPPER_WALL, "Waxed Copper Wall");
			builder.add(SSWPBlocks.WAXED_COPPER_FENCE, "Waxed Copper Fence");
			builder.add(SSWPBlocks.WAXED_COPPER_FENCE_GATE, "Waxed Copper Fence Gate");
			builder.add(SSWPBlocks.WAXED_COPPER_BARS, "Waxed Copper Bars");
			builder.add(SSWPBlocks.WAXED_COPPER_PRESSURE_PLATE, "Waxed Copper Pressure Plate");
			builder.add(SSWPBlocks.WAXED_COPPER_BUTTON, "Waxed Copper Button");
			builder.add(SSWPBlocks.WAXED_COPPER_CHAIN, "Waxed Copper Chain");
			builder.add(SSWPBlocks.WAXED_CHISELED_COPPER_SLAB, "Waxed Chiseled Copper Slab");
			builder.add(SSWPBlocks.WAXED_CHISELED_COPPER_STAIRS, "Waxed Chiseled Copper Stairs");
			builder.add(SSWPBlocks.WAXED_CHISELED_COPPER_WALL, "Waxed Chiseled Copper Wall");
			builder.add(SSWPBlocks.WAXED_COPPER_GRATE_SLAB, "Waxed Copper Grate Slab");
			builder.add(SSWPBlocks.WAXED_COPPER_GRATE_STAIRS, "Waxed Copper Grate Stairs");
			builder.add(SSWPBlocks.WAXED_COPPER_GRATE_WALL, "Waxed Copper Grate Wall");
			builder.add(SSWPBlocks.WAXED_CUT_COPPER_WALL, "Waxed Cut Copper Wall");
			builder.add(SSWPBlocks.WAXED_EXPOSED_COPPER_SLAB, "Waxed Exposed Copper Slab");
			builder.add(SSWPBlocks.WAXED_EXPOSED_COPPER_STAIRS, "Waxed Exposed Copper Stairs");
			builder.add(SSWPBlocks.WAXED_EXPOSED_COPPER_WALL, "Waxed Exposed Copper Wall");
			builder.add(SSWPBlocks.WAXED_EXPOSED_COPPER_FENCE, "Waxed Exposed Copper Fence");
			builder.add(SSWPBlocks.WAXED_EXPOSED_COPPER_FENCE_GATE, "Waxed Exposed Copper Fence Gate");
			builder.add(SSWPBlocks.WAXED_EXPOSED_COPPER_BARS, "Waxed Exposed Copper Bars");
			builder.add(SSWPBlocks.WAXED_EXPOSED_COPPER_PRESSURE_PLATE, "Waxed Exposed Copper Pressure Plate");
			builder.add(SSWPBlocks.WAXED_EXPOSED_COPPER_BUTTON, "Waxed Exposed Copper Button");
			builder.add(SSWPBlocks.WAXED_EXPOSED_COPPER_CHAIN, "Waxed Exposed Copper Chain");
			builder.add(SSWPBlocks.WAXED_EXPOSED_CHISELED_COPPER_SLAB, "Waxed Exposed Chiseled Copper Slab");
			builder.add(SSWPBlocks.WAXED_EXPOSED_CHISELED_COPPER_STAIRS, "Waxed Exposed Chiseled Copper Stairs");
			builder.add(SSWPBlocks.WAXED_EXPOSED_CHISELED_COPPER_WALL, "Waxed Exposed Chiseled Copper Wall");
			builder.add(SSWPBlocks.WAXED_EXPOSED_COPPER_GRATE_SLAB, "Waxed Exposed Copper Grate Slab");
			builder.add(SSWPBlocks.WAXED_EXPOSED_COPPER_GRATE_STAIRS, "Waxed Exposed Copper Grate Stairs");
			builder.add(SSWPBlocks.WAXED_EXPOSED_COPPER_GRATE_WALL, "Waxed Exposed Copper Grate Wall");
			builder.add(SSWPBlocks.WAXED_EXPOSED_CUT_COPPER_WALL, "Waxed Exposed Cut Copper Wall");
			builder.add(SSWPBlocks.WAXED_WEATHERED_COPPER_SLAB, "Waxed Weathered Copper Slab");
			builder.add(SSWPBlocks.WAXED_WEATHERED_COPPER_STAIRS, "Waxed Weathered Copper Stairs");
			builder.add(SSWPBlocks.WAXED_WEATHERED_COPPER_WALL, "Waxed Weathered Copper Wall");
			builder.add(SSWPBlocks.WAXED_WEATHERED_COPPER_FENCE, "Waxed Weathered Copper Fence");
			builder.add(SSWPBlocks.WAXED_WEATHERED_COPPER_FENCE_GATE, "Waxed Weathered Copper Fence Gate");
			builder.add(SSWPBlocks.WAXED_WEATHERED_COPPER_BARS, "Waxed Weathered Copper Bars");
			builder.add(SSWPBlocks.WAXED_WEATHERED_COPPER_PRESSURE_PLATE, "Waxed Weathered Copper Pressure Plate");
			builder.add(SSWPBlocks.WAXED_WEATHERED_COPPER_BUTTON, "Waxed Weathered Copper Button");
			builder.add(SSWPBlocks.WAXED_WEATHERED_COPPER_CHAIN, "Waxed Weathered Copper Chain");
			builder.add(SSWPBlocks.WAXED_WEATHERED_CHISELED_COPPER_SLAB, "Waxed Weathered Chiseled Copper Slab");
			builder.add(SSWPBlocks.WAXED_WEATHERED_CHISELED_COPPER_STAIRS, "Waxed Weathered Chiseled Copper Stairs");
			builder.add(SSWPBlocks.WAXED_WEATHERED_CHISELED_COPPER_WALL, "Waxed Weathered Chiseled Copper Wall");
			builder.add(SSWPBlocks.WAXED_WEATHERED_COPPER_GRATE_SLAB, "Waxed Weathered Copper Grate Slab");
			builder.add(SSWPBlocks.WAXED_WEATHERED_COPPER_GRATE_STAIRS, "Waxed Weathered Copper Grate Stairs");
			builder.add(SSWPBlocks.WAXED_WEATHERED_COPPER_GRATE_WALL, "Waxed Weathered Copper Grate Wall");
			builder.add(SSWPBlocks.WAXED_WEATHERED_CUT_COPPER_WALL, "Waxed Weathered Cut Copper Wall");
			builder.add(SSWPBlocks.WAXED_OXIDIZED_COPPER_SLAB, "Waxed Oxidized Copper Slab");
			builder.add(SSWPBlocks.WAXED_OXIDIZED_COPPER_STAIRS, "Waxed Oxidized Copper Stairs");
			builder.add(SSWPBlocks.WAXED_OXIDIZED_COPPER_WALL, "Waxed Oxidized Copper Wall");
			builder.add(SSWPBlocks.WAXED_OXIDIZED_COPPER_FENCE, "Waxed Oxidized Copper Fence");
			builder.add(SSWPBlocks.WAXED_OXIDIZED_COPPER_FENCE_GATE, "Waxed Oxidized Copper Fence Gate");
			builder.add(SSWPBlocks.WAXED_OXIDIZED_COPPER_BARS, "Waxed Oxidized Copper Bars");
			builder.add(SSWPBlocks.WAXED_OXIDIZED_COPPER_PRESSURE_PLATE, "Waxed Oxidized Copper Pressure Plate");
			builder.add(SSWPBlocks.WAXED_OXIDIZED_COPPER_BUTTON, "Waxed Oxidized Copper Button");
			builder.add(SSWPBlocks.WAXED_OXIDIZED_COPPER_CHAIN, "Waxed Oxidized Copper Chain");
			builder.add(SSWPBlocks.WAXED_OXIDIZED_CHISELED_COPPER_SLAB, "Waxed Oxidized Chiseled Copper Slab");
			builder.add(SSWPBlocks.WAXED_OXIDIZED_CHISELED_COPPER_STAIRS, "Waxed Oxidized Chiseled Copper Stairs");
			builder.add(SSWPBlocks.WAXED_OXIDIZED_CHISELED_COPPER_WALL, "Waxed Oxidized Chiseled Copper Wall");
			builder.add(SSWPBlocks.WAXED_OXIDIZED_COPPER_GRATE_SLAB, "Waxed Oxidized Copper Grate Slab");
			builder.add(SSWPBlocks.WAXED_OXIDIZED_COPPER_GRATE_STAIRS, "Waxed Oxidized Copper Grate Stairs");
			builder.add(SSWPBlocks.WAXED_OXIDIZED_COPPER_GRATE_WALL, "Waxed Oxidized Copper Grate Wall");
			builder.add(SSWPBlocks.WAXED_OXIDIZED_CUT_COPPER_WALL, "Waxed Oxidized Cut Copper Wall");
			builder.add(SSWPBlocks.WHITE_WOOL_SLAB, "White Wool Slab");
			builder.add(SSWPBlocks.WHITE_WOOL_STAIRS, "White Wool Stairs");
			builder.add(SSWPBlocks.WHITE_WOOL_WALL, "White Wool Wall");
			builder.add(SSWPBlocks.LIGHT_GRAY_WOOL_SLAB, "Light Gray Wool Slab");
			builder.add(SSWPBlocks.LIGHT_GRAY_WOOL_STAIRS, "Light Gray Wool Stairs");
			builder.add(SSWPBlocks.LIGHT_GRAY_WOOL_WALL, "Light Gray Wool Wall");
			builder.add(SSWPBlocks.GRAY_WOOL_SLAB, "Gray Wool Slab");
			builder.add(SSWPBlocks.GRAY_WOOL_STAIRS, "Gray Wool Stairs");
			builder.add(SSWPBlocks.GRAY_WOOL_WALL, "Gray Wool Wall");
			builder.add(SSWPBlocks.BLACK_WOOL_SLAB, "Black Wool Slab");
			builder.add(SSWPBlocks.BLACK_WOOL_STAIRS, "Black Wool Stairs");
			builder.add(SSWPBlocks.BLACK_WOOL_WALL, "Black Wool Wall");
			builder.add(SSWPBlocks.BROWN_WOOL_SLAB, "Brown Wool Slab");
			builder.add(SSWPBlocks.BROWN_WOOL_STAIRS, "Brown Wool Stairs");
			builder.add(SSWPBlocks.BROWN_WOOL_WALL, "Brown Wool Wall");
			builder.add(SSWPBlocks.RED_WOOL_SLAB, "Red Wool Slab");
			builder.add(SSWPBlocks.RED_WOOL_STAIRS, "Red Wool Stairs");
			builder.add(SSWPBlocks.RED_WOOL_WALL, "Red Wool Wall");
			builder.add(SSWPBlocks.ORANGE_WOOL_SLAB, "Orange Wool Slab");
			builder.add(SSWPBlocks.ORANGE_WOOL_STAIRS, "Orange Wool Stairs");
			builder.add(SSWPBlocks.ORANGE_WOOL_WALL, "Orange Wool Wall");
			builder.add(SSWPBlocks.YELLOW_WOOL_SLAB, "Yellow Wool Slab");
			builder.add(SSWPBlocks.YELLOW_WOOL_STAIRS, "Yellow Wool Stairs");
			builder.add(SSWPBlocks.YELLOW_WOOL_WALL, "Yellow Wool Wall");
			builder.add(SSWPBlocks.LIME_WOOL_SLAB, "Lime Wool Slab");
			builder.add(SSWPBlocks.LIME_WOOL_STAIRS, "Lime Wool Stairs");
			builder.add(SSWPBlocks.LIME_WOOL_WALL, "Lime Wool Wall");
			builder.add(SSWPBlocks.GREEN_WOOL_SLAB, "Green Wool Slab");
			builder.add(SSWPBlocks.GREEN_WOOL_STAIRS, "Green Wool Stairs");
			builder.add(SSWPBlocks.GREEN_WOOL_WALL, "Green Wool Wall");
			builder.add(SSWPBlocks.CYAN_WOOL_SLAB, "Cyan Wool Slab");
			builder.add(SSWPBlocks.CYAN_WOOL_STAIRS, "Cyan Wool Stairs");
			builder.add(SSWPBlocks.CYAN_WOOL_WALL, "Cyan Wool Wall");
			builder.add(SSWPBlocks.LIGHT_BLUE_WOOL_SLAB, "Light Blue Wool Slab");
			builder.add(SSWPBlocks.LIGHT_BLUE_WOOL_STAIRS, "Light Blue Wool Stairs");
			builder.add(SSWPBlocks.LIGHT_BLUE_WOOL_WALL, "Light Blue Wool Wall");
			builder.add(SSWPBlocks.BLUE_WOOL_SLAB, "Blue Wool Slab");
			builder.add(SSWPBlocks.BLUE_WOOL_STAIRS, "Blue Wool Stairs");
			builder.add(SSWPBlocks.BLUE_WOOL_WALL, "Blue Wool Wall");
			builder.add(SSWPBlocks.PURPLE_WOOL_SLAB, "Purple Wool Slab");
			builder.add(SSWPBlocks.PURPLE_WOOL_STAIRS, "Purple Wool Stairs");
			builder.add(SSWPBlocks.PURPLE_WOOL_WALL, "Purple Wool Wall");
			builder.add(SSWPBlocks.MAGENTA_WOOL_SLAB, "Magenta Wool Slab");
			builder.add(SSWPBlocks.MAGENTA_WOOL_STAIRS, "Magenta Wool Stairs");
			builder.add(SSWPBlocks.MAGENTA_WOOL_WALL, "Magenta Wool Wall");
			builder.add(SSWPBlocks.PINK_WOOL_SLAB, "Pink Wool Slab");
			builder.add(SSWPBlocks.PINK_WOOL_STAIRS, "Pink Wool Stairs");
			builder.add(SSWPBlocks.PINK_WOOL_WALL, "Pink Wool Wall");
			builder.add(SSWPBlocks.TERRACOTTA_SLAB, "Terracotta Slab");
			builder.add(SSWPBlocks.TERRACOTTA_STAIRS, "Terracotta Stairs");
			builder.add(SSWPBlocks.TERRACOTTA_WALL, "Terracotta Wall");
			builder.add(SSWPBlocks.WHITE_TERRACOTTA_SLAB, "White Terracotta Slab");
			builder.add(SSWPBlocks.WHITE_TERRACOTTA_STAIRS, "White Terracotta Stairs");
			builder.add(SSWPBlocks.WHITE_TERRACOTTA_WALL, "White Terracotta Wall");
			builder.add(SSWPBlocks.LIGHT_GRAY_TERRACOTTA_SLAB, "Light Gray Terracotta Slab");
			builder.add(SSWPBlocks.LIGHT_GRAY_TERRACOTTA_STAIRS, "Light Gray Terracotta Stairs");
			builder.add(SSWPBlocks.LIGHT_GRAY_TERRACOTTA_WALL, "Light Gray Terracotta Wall");
			builder.add(SSWPBlocks.GRAY_TERRACOTTA_SLAB, "Gray Terracotta Slab");
			builder.add(SSWPBlocks.GRAY_TERRACOTTA_STAIRS, "Gray Terracotta Stairs");
			builder.add(SSWPBlocks.GRAY_TERRACOTTA_WALL, "Gray Terracotta Wall");
			builder.add(SSWPBlocks.BLACK_TERRACOTTA_SLAB, "Black Terracotta Slab");
			builder.add(SSWPBlocks.BLACK_TERRACOTTA_STAIRS, "Black Terracotta Stairs");
			builder.add(SSWPBlocks.BLACK_TERRACOTTA_WALL, "Black Terracotta Wall");
			builder.add(SSWPBlocks.BROWN_TERRACOTTA_SLAB, "Brown Terracotta Slab");
			builder.add(SSWPBlocks.BROWN_TERRACOTTA_STAIRS, "Brown Terracotta Stairs");
			builder.add(SSWPBlocks.BROWN_TERRACOTTA_WALL, "Brown Terracotta Wall");
			builder.add(SSWPBlocks.RED_TERRACOTTA_SLAB, "Red Terracotta Slab");
			builder.add(SSWPBlocks.RED_TERRACOTTA_STAIRS, "Red Terracotta Stairs");
			builder.add(SSWPBlocks.RED_TERRACOTTA_WALL, "Red Terracotta Wall");
			builder.add(SSWPBlocks.ORANGE_TERRACOTTA_SLAB, "Orange Terracotta Slab");
			builder.add(SSWPBlocks.ORANGE_TERRACOTTA_STAIRS, "Orange Terracotta Stairs");
			builder.add(SSWPBlocks.ORANGE_TERRACOTTA_WALL, "Orange Terracotta Wall");
			builder.add(SSWPBlocks.YELLOW_TERRACOTTA_SLAB, "Yellow Terracotta Slab");
			builder.add(SSWPBlocks.YELLOW_TERRACOTTA_STAIRS, "Yellow Terracotta Stairs");
			builder.add(SSWPBlocks.YELLOW_TERRACOTTA_WALL, "Yellow Terracotta Wall");
			builder.add(SSWPBlocks.LIME_TERRACOTTA_SLAB, "Lime Terracotta Slab");
			builder.add(SSWPBlocks.LIME_TERRACOTTA_STAIRS, "Lime Terracotta Stairs");
			builder.add(SSWPBlocks.LIME_TERRACOTTA_WALL, "Lime Terracotta Wall");
			builder.add(SSWPBlocks.GREEN_TERRACOTTA_SLAB, "Green Terracotta Slab");
			builder.add(SSWPBlocks.GREEN_TERRACOTTA_STAIRS, "Green Terracotta Stairs");
			builder.add(SSWPBlocks.GREEN_TERRACOTTA_WALL, "Green Terracotta Wall");
			builder.add(SSWPBlocks.CYAN_TERRACOTTA_SLAB, "Cyan Terracotta Slab");
			builder.add(SSWPBlocks.CYAN_TERRACOTTA_STAIRS, "Cyan Terracotta Stairs");
			builder.add(SSWPBlocks.CYAN_TERRACOTTA_WALL, "Cyan Terracotta Wall");
			builder.add(SSWPBlocks.LIGHT_BLUE_TERRACOTTA_SLAB, "Light Blue Terracotta Slab");
			builder.add(SSWPBlocks.LIGHT_BLUE_TERRACOTTA_STAIRS, "Light Blue Terracotta Stairs");
			builder.add(SSWPBlocks.LIGHT_BLUE_TERRACOTTA_WALL, "Light Blue Terracotta Wall");
			builder.add(SSWPBlocks.BLUE_TERRACOTTA_SLAB, "Blue Terracotta Slab");
			builder.add(SSWPBlocks.BLUE_TERRACOTTA_STAIRS, "Blue Terracotta Stairs");
			builder.add(SSWPBlocks.BLUE_TERRACOTTA_WALL, "Blue Terracotta Wall");
			builder.add(SSWPBlocks.PURPLE_TERRACOTTA_SLAB, "Purple Terracotta Slab");
			builder.add(SSWPBlocks.PURPLE_TERRACOTTA_STAIRS, "Purple Terracotta Stairs");
			builder.add(SSWPBlocks.PURPLE_TERRACOTTA_WALL, "Purple Terracotta Wall");
			builder.add(SSWPBlocks.MAGENTA_TERRACOTTA_SLAB, "Magenta Terracotta Slab");
			builder.add(SSWPBlocks.MAGENTA_TERRACOTTA_STAIRS, "Magenta Terracotta Stairs");
			builder.add(SSWPBlocks.MAGENTA_TERRACOTTA_WALL, "Magenta Terracotta Wall");
			builder.add(SSWPBlocks.PINK_TERRACOTTA_SLAB, "Pink Terracotta Slab");
			builder.add(SSWPBlocks.PINK_TERRACOTTA_STAIRS, "Pink Terracotta Stairs");
			builder.add(SSWPBlocks.PINK_TERRACOTTA_WALL, "Pink Terracotta Wall");
			builder.add(SSWPBlocks.WHITE_CONCRETE_SLAB, "White Concrete Slab");
			builder.add(SSWPBlocks.WHITE_CONCRETE_STAIRS, "White Concrete Stairs");
			builder.add(SSWPBlocks.WHITE_CONCRETE_WALL, "White Concrete Wall");
			builder.add(SSWPBlocks.LIGHT_GRAY_CONCRETE_SLAB, "Light Gray Concrete Slab");
			builder.add(SSWPBlocks.LIGHT_GRAY_CONCRETE_STAIRS, "Light Gray Concrete Stairs");
			builder.add(SSWPBlocks.LIGHT_GRAY_CONCRETE_WALL, "Light Gray Concrete Wall");
			builder.add(SSWPBlocks.GRAY_CONCRETE_SLAB, "Gray Concrete Slab");
			builder.add(SSWPBlocks.GRAY_CONCRETE_STAIRS, "Gray Concrete Stairs");
			builder.add(SSWPBlocks.GRAY_CONCRETE_WALL, "Gray Concrete Wall");
			builder.add(SSWPBlocks.BLACK_CONCRETE_SLAB, "Black Concrete Slab");
			builder.add(SSWPBlocks.BLACK_CONCRETE_STAIRS, "Black Concrete Stairs");
			builder.add(SSWPBlocks.BLACK_CONCRETE_WALL, "Black Concrete Wall");
			builder.add(SSWPBlocks.BROWN_CONCRETE_SLAB, "Brown Concrete Slab");
			builder.add(SSWPBlocks.BROWN_CONCRETE_STAIRS, "Brown Concrete Stairs");
			builder.add(SSWPBlocks.BROWN_CONCRETE_WALL, "Brown Concrete Wall");
			builder.add(SSWPBlocks.RED_CONCRETE_SLAB, "Red Concrete Slab");
			builder.add(SSWPBlocks.RED_CONCRETE_STAIRS, "Red Concrete Stairs");
			builder.add(SSWPBlocks.RED_CONCRETE_WALL, "Red Concrete Wall");
			builder.add(SSWPBlocks.ORANGE_CONCRETE_SLAB, "Orange Concrete Slab");
			builder.add(SSWPBlocks.ORANGE_CONCRETE_STAIRS, "Orange Concrete Stairs");
			builder.add(SSWPBlocks.ORANGE_CONCRETE_WALL, "Orange Concrete Wall");
			builder.add(SSWPBlocks.YELLOW_CONCRETE_SLAB, "Yellow Concrete Slab");
			builder.add(SSWPBlocks.YELLOW_CONCRETE_STAIRS, "Yellow Concrete Stairs");
			builder.add(SSWPBlocks.YELLOW_CONCRETE_WALL, "Yellow Concrete Wall");
			builder.add(SSWPBlocks.LIME_CONCRETE_SLAB, "Lime Concrete Slab");
			builder.add(SSWPBlocks.LIME_CONCRETE_STAIRS, "Lime Concrete Stairs");
			builder.add(SSWPBlocks.LIME_CONCRETE_WALL, "Lime Concrete Wall");
			builder.add(SSWPBlocks.GREEN_CONCRETE_SLAB, "Green Concrete Slab");
			builder.add(SSWPBlocks.GREEN_CONCRETE_STAIRS, "Green Concrete Stairs");
			builder.add(SSWPBlocks.GREEN_CONCRETE_WALL, "Green Concrete Wall");
			builder.add(SSWPBlocks.CYAN_CONCRETE_SLAB, "Cyan Concrete Slab");
			builder.add(SSWPBlocks.CYAN_CONCRETE_STAIRS, "Cyan Concrete Stairs");
			builder.add(SSWPBlocks.CYAN_CONCRETE_WALL, "Cyan Concrete Wall");
			builder.add(SSWPBlocks.LIGHT_BLUE_CONCRETE_SLAB, "Light Blue Concrete Slab");
			builder.add(SSWPBlocks.LIGHT_BLUE_CONCRETE_STAIRS, "Light Blue Concrete Stairs");
			builder.add(SSWPBlocks.LIGHT_BLUE_CONCRETE_WALL, "Light Blue Concrete Wall");
			builder.add(SSWPBlocks.BLUE_CONCRETE_SLAB, "Blue Concrete Slab");
			builder.add(SSWPBlocks.BLUE_CONCRETE_STAIRS, "Blue Concrete Stairs");
			builder.add(SSWPBlocks.BLUE_CONCRETE_WALL, "Blue Concrete Wall");
			builder.add(SSWPBlocks.PURPLE_CONCRETE_SLAB, "Purple Concrete Slab");
			builder.add(SSWPBlocks.PURPLE_CONCRETE_STAIRS, "Purple Concrete Stairs");
			builder.add(SSWPBlocks.PURPLE_CONCRETE_WALL, "Purple Concrete Wall");
			builder.add(SSWPBlocks.MAGENTA_CONCRETE_SLAB, "Magenta Concrete Slab");
			builder.add(SSWPBlocks.MAGENTA_CONCRETE_STAIRS, "Magenta Concrete Stairs");
			builder.add(SSWPBlocks.MAGENTA_CONCRETE_WALL, "Magenta Concrete Wall");
			builder.add(SSWPBlocks.PINK_CONCRETE_SLAB, "Pink Concrete Slab");
			builder.add(SSWPBlocks.PINK_CONCRETE_STAIRS, "Pink Concrete Stairs");
			builder.add(SSWPBlocks.PINK_CONCRETE_WALL, "Pink Concrete Wall");
			builder.add(SSWPBlocks.GLASS_SLAB, "Glass Slab");
			builder.add(SSWPBlocks.GLASS_STAIRS, "Glass Stairs");
			builder.add(SSWPBlocks.GLASS_WALL, "Glass Wall");
			builder.add(SSWPBlocks.TINTED_GLASS_SLAB, "Tinted Glass Slab");
			builder.add(SSWPBlocks.TINTED_GLASS_STAIRS, "Tinted Glass Stairs");
			builder.add(SSWPBlocks.TINTED_GLASS_WALL, "Tinted Glass Wall");
			builder.add(SSWPBlocks.TINTED_GLASS_PANE, "Tinted Glass Pane");
			builder.add(SSWPBlocks.WHITE_STAINED_GLASS_SLAB, "White Stained Glass Slab");
			builder.add(SSWPBlocks.WHITE_STAINED_GLASS_STAIRS, "White Stained Glass Stairs");
			builder.add(SSWPBlocks.WHITE_STAINED_GLASS_WALL, "White Stained Glass Wall");
			builder.add(SSWPBlocks.LIGHT_GRAY_STAINED_GLASS_SLAB, "Light Gray Stained Glass Slab");
			builder.add(SSWPBlocks.LIGHT_GRAY_STAINED_GLASS_STAIRS, "Light Gray Stained Glass Stairs");
			builder.add(SSWPBlocks.LIGHT_GRAY_STAINED_GLASS_WALL, "Light Gray Stained Glass Wall");
			builder.add(SSWPBlocks.GRAY_STAINED_GLASS_SLAB, "Gray Stained Glass Slab");
			builder.add(SSWPBlocks.GRAY_STAINED_GLASS_STAIRS, "Gray Stained Glass Stairs");
			builder.add(SSWPBlocks.GRAY_STAINED_GLASS_WALL, "Gray Stained Glass Wall");
			builder.add(SSWPBlocks.BLACK_STAINED_GLASS_SLAB, "Black Stained Glass Slab");
			builder.add(SSWPBlocks.BLACK_STAINED_GLASS_STAIRS, "Black Stained Glass Stairs");
			builder.add(SSWPBlocks.BLACK_STAINED_GLASS_WALL, "Black Stained Glass Wall");
			builder.add(SSWPBlocks.BROWN_STAINED_GLASS_SLAB, "Brown Stained Glass Slab");
			builder.add(SSWPBlocks.BROWN_STAINED_GLASS_STAIRS, "Brown Stained Glass Stairs");
			builder.add(SSWPBlocks.BROWN_STAINED_GLASS_WALL, "Brown Stained Glass Wall");
			builder.add(SSWPBlocks.RED_STAINED_GLASS_SLAB, "Red Stained Glass Slab");
			builder.add(SSWPBlocks.RED_STAINED_GLASS_STAIRS, "Red Stained Glass Stairs");
			builder.add(SSWPBlocks.RED_STAINED_GLASS_WALL, "Red Stained Glass Wall");
			builder.add(SSWPBlocks.ORANGE_STAINED_GLASS_SLAB, "Orange Stained Glass Slab");
			builder.add(SSWPBlocks.ORANGE_STAINED_GLASS_STAIRS, "Orange Stained Glass Stairs");
			builder.add(SSWPBlocks.ORANGE_STAINED_GLASS_WALL, "Orange Stained Glass Wall");
			builder.add(SSWPBlocks.YELLOW_STAINED_GLASS_SLAB, "Yellow Stained Glass Slab");
			builder.add(SSWPBlocks.YELLOW_STAINED_GLASS_STAIRS, "Yellow Stained Glass Stairs");
			builder.add(SSWPBlocks.YELLOW_STAINED_GLASS_WALL, "Yellow Stained Glass Wall");
			builder.add(SSWPBlocks.LIME_STAINED_GLASS_SLAB, "Lime Stained Glass Slab");
			builder.add(SSWPBlocks.LIME_STAINED_GLASS_STAIRS, "Lime Stained Glass Stairs");
			builder.add(SSWPBlocks.LIME_STAINED_GLASS_WALL, "Lime Stained Glass Wall");
			builder.add(SSWPBlocks.GREEN_STAINED_GLASS_SLAB, "Green Stained Glass Slab");
			builder.add(SSWPBlocks.GREEN_STAINED_GLASS_STAIRS, "Green Stained Glass Stairs");
			builder.add(SSWPBlocks.GREEN_STAINED_GLASS_WALL, "Green Stained Glass Wall");
			builder.add(SSWPBlocks.CYAN_STAINED_GLASS_SLAB, "Cyan Stained Glass Slab");
			builder.add(SSWPBlocks.CYAN_STAINED_GLASS_STAIRS, "Cyan Stained Glass Stairs");
			builder.add(SSWPBlocks.CYAN_STAINED_GLASS_WALL, "Cyan Stained Glass Wall");
			builder.add(SSWPBlocks.LIGHT_BLUE_STAINED_GLASS_SLAB, "Light Blue Stained Glass Slab");
			builder.add(SSWPBlocks.LIGHT_BLUE_STAINED_GLASS_STAIRS, "Light Blue Stained Glass Stairs");
			builder.add(SSWPBlocks.LIGHT_BLUE_STAINED_GLASS_WALL, "Light Blue Stained Glass Wall");
			builder.add(SSWPBlocks.BLUE_STAINED_GLASS_SLAB, "Blue Stained Glass Slab");
			builder.add(SSWPBlocks.BLUE_STAINED_GLASS_STAIRS, "Blue Stained Glass Stairs");
			builder.add(SSWPBlocks.BLUE_STAINED_GLASS_WALL, "Blue Stained Glass Wall");
			builder.add(SSWPBlocks.PURPLE_STAINED_GLASS_SLAB, "Purple Stained Glass Slab");
			builder.add(SSWPBlocks.PURPLE_STAINED_GLASS_STAIRS, "Purple Stained Glass Stairs");
			builder.add(SSWPBlocks.PURPLE_STAINED_GLASS_WALL, "Purple Stained Glass Wall");
			builder.add(SSWPBlocks.MAGENTA_STAINED_GLASS_SLAB, "Magenta Stained Glass Slab");
			builder.add(SSWPBlocks.MAGENTA_STAINED_GLASS_STAIRS, "Magenta Stained Glass Stairs");
			builder.add(SSWPBlocks.MAGENTA_STAINED_GLASS_WALL, "Magenta Stained Glass Wall");
			builder.add(SSWPBlocks.PINK_STAINED_GLASS_SLAB, "Pink Stained Glass Slab");
			builder.add(SSWPBlocks.PINK_STAINED_GLASS_STAIRS, "Pink Stained Glass Stairs");
			builder.add(SSWPBlocks.PINK_STAINED_GLASS_WALL, "Pink Stained Glass Wall");
			builder.add(SSWPBlocks.GRASS_SLAB, "Grass Slab");
			builder.add(SSWPBlocks.GRASS_STAIRS, "Grass Stairs");
			builder.add(SSWPBlocks.GRASS_WALL, "Grass Wall");
			builder.add(SSWPBlocks.PODZOL_SLAB, "Podzol Slab");
			builder.add(SSWPBlocks.PODZOL_STAIRS, "Podzol Stairs");
			builder.add(SSWPBlocks.PODZOL_WALL, "Podzol Wall");
			builder.add(SSWPBlocks.MYCELIUM_SLAB, "Mycelium Slab");
			builder.add(SSWPBlocks.MYCELIUM_STAIRS, "Mycelium Stairs");
			builder.add(SSWPBlocks.MYCELIUM_WALL, "Mycelium Wall");
			builder.add(SSWPBlocks.DIRT_PATH_SLAB, "Dirt Path Slab");
			builder.add(SSWPBlocks.DIRT_PATH_STAIRS, "Dirt Path Stairs");
			builder.add(SSWPBlocks.DIRT_PATH_WALL, "Dirt Path Wall");
			builder.add(SSWPBlocks.DIRT_SLAB, "Dirt Slab");
			builder.add(SSWPBlocks.DIRT_STAIRS, "Dirt Stairs");
			builder.add(SSWPBlocks.DIRT_WALL, "Dirt Wall");
			builder.add(SSWPBlocks.COARSE_DIRT_SLAB, "Coarse Dirt Slab");
			builder.add(SSWPBlocks.COARSE_DIRT_STAIRS, "Coarse Dirt Stairs");
			builder.add(SSWPBlocks.COARSE_DIRT_WALL, "Coarse Dirt Wall");
			builder.add(SSWPBlocks.ROOTED_DIRT_SLAB, "Rooted Dirt Slab");
			builder.add(SSWPBlocks.ROOTED_DIRT_STAIRS, "Rooted Dirt Stairs");
			builder.add(SSWPBlocks.ROOTED_DIRT_WALL, "Rooted Dirt Wall");
			builder.add(SSWPBlocks.MUD_SLAB, "Mud Slab");
			builder.add(SSWPBlocks.MUD_STAIRS, "Mud Stairs");
			builder.add(SSWPBlocks.MUD_WALL, "Mud Wall");
			builder.add(SSWPBlocks.CLAY_SLAB, "Clay Slab");
			builder.add(SSWPBlocks.CLAY_STAIRS, "Clay Stairs");
			builder.add(SSWPBlocks.CLAY_WALL, "Clay Wall");
			builder.add(SSWPBlocks.ICE_SLAB, "Ice Slab");
			builder.add(SSWPBlocks.ICE_STAIRS, "Ice Stairs");
			builder.add(SSWPBlocks.ICE_WALL, "Ice Wall");
			builder.add(SSWPBlocks.PACKED_ICE_SLAB, "Packed Ice Slab");
			builder.add(SSWPBlocks.PACKED_ICE_STAIRS, "Packed Ice Stairs");
			builder.add(SSWPBlocks.PACKED_ICE_WALL, "Packed Ice Wall");
			builder.add(SSWPBlocks.BLUE_ICE_SLAB, "Blue Ice Slab");
			builder.add(SSWPBlocks.BLUE_ICE_STAIRS, "Blue Ice Stairs");
			builder.add(SSWPBlocks.BLUE_ICE_WALL, "Blue Ice Wall");
			builder.add(SSWPBlocks.SNOW_SLAB, "Snow Slab");
			builder.add(SSWPBlocks.SNOW_STAIRS, "Snow Stairs");
			builder.add(SSWPBlocks.SNOW_WALL, "Snow Wall");
			builder.add(SSWPBlocks.MOSS_SLAB, "Moss Slab");
			builder.add(SSWPBlocks.MOSS_STAIRS, "Moss Stairs");
			builder.add(SSWPBlocks.MOSS_WALL, "Moss Wall");
			builder.add(SSWPBlocks.CALCITE_SLAB, "Calcite Slab");
			builder.add(SSWPBlocks.CALCITE_STAIRS, "Calcite Stairs");
			builder.add(SSWPBlocks.CALCITE_WALL, "Calcite Wall");
			builder.add(SSWPBlocks.DRIPSTONE_SLAB, "Dripstone Slab");
			builder.add(SSWPBlocks.DRIPSTONE_STAIRS, "Dripstone Stairs");
			builder.add(SSWPBlocks.DRIPSTONE_WALL, "Dripstone Wall");
			builder.add(SSWPBlocks.MAGMA_SLAB, "Magma Slab");
			builder.add(SSWPBlocks.MAGMA_STAIRS, "Magma Stairs");
			builder.add(SSWPBlocks.MAGMA_WALL, "Magma Wall");
			builder.add(SSWPBlocks.OBSIDIAN_SLAB, "Obsidian Slab");
			builder.add(SSWPBlocks.OBSIDIAN_STAIRS, "Obsidian Stairs");
			builder.add(SSWPBlocks.OBSIDIAN_WALL, "Obsidian Wall");
			builder.add(SSWPBlocks.CRYING_OBSIDIAN_SLAB, "Crying Obsidian Slab");
			builder.add(SSWPBlocks.CRYING_OBSIDIAN_STAIRS, "Crying Obsidian Stairs");
			builder.add(SSWPBlocks.CRYING_OBSIDIAN_WALL, "Crying Obsidian Wall");
			builder.add(SSWPBlocks.CRIMSON_NYLIUM_SLAB, "Crimson Nylium Slab");
			builder.add(SSWPBlocks.CRIMSON_NYLIUM_STAIRS, "Crimson Nylium Stairs");
			builder.add(SSWPBlocks.CRIMSON_NYLIUM_WALL, "Crimson Nylium Wall");
			builder.add(SSWPBlocks.WARPED_NYLIUM_SLAB, "Warped Nylium Slab");
			builder.add(SSWPBlocks.WARPED_NYLIUM_STAIRS, "Warped Nylium Stairs");
			builder.add(SSWPBlocks.WARPED_NYLIUM_WALL, "Warped Nylium Wall");
			builder.add(SSWPBlocks.SOUL_SAND_SLAB, "Soul Sand Slab");
			builder.add(SSWPBlocks.SOUL_SAND_STAIRS, "Soul Sand Stairs");
			builder.add(SSWPBlocks.SOUL_SAND_WALL, "Soul Sand Wall");
			builder.add(SSWPBlocks.SOUL_SOIL_SLAB, "Soul Soil Slab");
			builder.add(SSWPBlocks.SOUL_SOIL_STAIRS, "Soul Soil Stairs");
			builder.add(SSWPBlocks.SOUL_SOIL_WALL, "Soul Soil Wall");
			builder.add(SSWPBlocks.BONE_SLAB, "Bone Slab");
			builder.add(SSWPBlocks.BONE_STAIRS, "Bone Stairs");
			builder.add(SSWPBlocks.BONE_WALL, "Bone Wall");
			builder.add(SSWPBlocks.COAL_ORE_SLAB, "Coal Ore Slab");
			builder.add(SSWPBlocks.COAL_ORE_STAIRS, "Coal Ore Stairs");
			builder.add(SSWPBlocks.COAL_ORE_WALL, "Coal Ore Wall");
			builder.add(SSWPBlocks.DEEPSLATE_COAL_ORE_SLAB, "Deepslate Coal Ore Slab");
			builder.add(SSWPBlocks.DEEPSLATE_COAL_ORE_STAIRS, "Deepslate Coal Ore Stairs");
			builder.add(SSWPBlocks.DEEPSLATE_COAL_ORE_WALL, "Deepslate Coal Ore Wall");
			builder.add(SSWPBlocks.IRON_ORE_SLAB, "Iron Ore Slab");
			builder.add(SSWPBlocks.IRON_ORE_STAIRS, "Iron Ore Stairs");
			builder.add(SSWPBlocks.IRON_ORE_WALL, "Iron Ore Wall");
			builder.add(SSWPBlocks.DEEPSLATE_IRON_ORE_SLAB, "Deepslate Iron Ore Slab");
			builder.add(SSWPBlocks.DEEPSLATE_IRON_ORE_STAIRS, "Deepslate Iron Ore Stairs");
			builder.add(SSWPBlocks.DEEPSLATE_IRON_ORE_WALL, "Deepslate Iron Ore Wall");
			builder.add(SSWPBlocks.COPPER_ORE_SLAB, "Copper Ore Slab");
			builder.add(SSWPBlocks.COPPER_ORE_STAIRS, "Copper Ore Stairs");
			builder.add(SSWPBlocks.COPPER_ORE_WALL, "Copper Ore Wall");
			builder.add(SSWPBlocks.DEEPSLATE_COPPER_ORE_SLAB, "Deepslate Copper Ore Slab");
			builder.add(SSWPBlocks.DEEPSLATE_COPPER_ORE_STAIRS, "Deepslate Copper Ore Stairs");
			builder.add(SSWPBlocks.DEEPSLATE_COPPER_ORE_WALL, "Deepslate Copper Ore Wall");
			builder.add(SSWPBlocks.GOLD_ORE_SLAB, "Gold Ore Slab");
			builder.add(SSWPBlocks.GOLD_ORE_STAIRS, "Gold Ore Stairs");
			builder.add(SSWPBlocks.GOLD_ORE_WALL, "Gold Ore Wall");
			builder.add(SSWPBlocks.DEEPSLATE_GOLD_ORE_SLAB, "Deepslate Gold Ore Slab");
			builder.add(SSWPBlocks.DEEPSLATE_GOLD_ORE_STAIRS, "Deepslate Gold Ore Stairs");
			builder.add(SSWPBlocks.DEEPSLATE_GOLD_ORE_WALL, "Deepslate Gold Ore Wall");
			builder.add(SSWPBlocks.REDSTONE_ORE_SLAB, "Redstone Ore Slab");
			builder.add(SSWPBlocks.REDSTONE_ORE_STAIRS, "Redstone Ore Stairs");
			builder.add(SSWPBlocks.REDSTONE_ORE_WALL, "Redstone Ore Wall");
			builder.add(SSWPBlocks.DEEPSLATE_REDSTONE_ORE_SLAB, "Deepslate Redstone Ore Slab");
			builder.add(SSWPBlocks.DEEPSLATE_REDSTONE_ORE_STAIRS, "Deepslate Redstone Ore Stairs");
			builder.add(SSWPBlocks.DEEPSLATE_REDSTONE_ORE_WALL, "Deepslate Redstone Ore Wall");
			builder.add(SSWPBlocks.EMERALD_ORE_SLAB, "Emerald Ore Slab");
			builder.add(SSWPBlocks.EMERALD_ORE_STAIRS, "Emerald Ore Stairs");
			builder.add(SSWPBlocks.EMERALD_ORE_WALL, "Emerald Ore Wall");
			builder.add(SSWPBlocks.DEEPSLATE_EMERALD_ORE_SLAB, "Deepslate Emerald Ore Slab");
			builder.add(SSWPBlocks.DEEPSLATE_EMERALD_ORE_STAIRS, "Deepslate Emerald Ore Stairs");
			builder.add(SSWPBlocks.DEEPSLATE_EMERALD_ORE_WALL, "Deepslate Emerald Ore Wall");
			builder.add(SSWPBlocks.LAPIS_ORE_SLAB, "Lapis Lazuli Ore Slab");
			builder.add(SSWPBlocks.LAPIS_ORE_STAIRS, "Lapis Lazuli Ore Stairs");
			builder.add(SSWPBlocks.LAPIS_ORE_WALL, "Lapis Lazuli Ore Wall");
			builder.add(SSWPBlocks.DEEPSLATE_LAPIS_ORE_SLAB, "Deepslate Lapis Lazuli Ore Slab");
			builder.add(SSWPBlocks.DEEPSLATE_LAPIS_ORE_STAIRS, "Deepslate Lapis Lazuli Ore Stairs");
			builder.add(SSWPBlocks.DEEPSLATE_LAPIS_ORE_WALL, "Deepslate Lapis Lazuli Ore Wall");
			builder.add(SSWPBlocks.DIAMOND_ORE_SLAB, "Diamond Ore Slab");
			builder.add(SSWPBlocks.DIAMOND_ORE_STAIRS, "Diamond Ore Stairs");
			builder.add(SSWPBlocks.DIAMOND_ORE_WALL, "Diamond Ore Wall");
			builder.add(SSWPBlocks.DEEPSLATE_DIAMOND_ORE_SLAB, "Deepslate Diamond Ore Slab");
			builder.add(SSWPBlocks.DEEPSLATE_DIAMOND_ORE_STAIRS, "Deepslate Diamond Ore Stairs");
			builder.add(SSWPBlocks.DEEPSLATE_DIAMOND_ORE_WALL, "Deepslate Diamond Ore Wall");
			builder.add(SSWPBlocks.NETHER_QUARTZ_ORE_SLAB, "Nether Quartz Ore Slab");
			builder.add(SSWPBlocks.NETHER_QUARTZ_ORE_STAIRS, "Nether Quartz Ore Stairs");
			builder.add(SSWPBlocks.NETHER_QUARTZ_ORE_WALL, "Nether Quartz Ore Wall");
			builder.add(SSWPBlocks.NETHER_GOLD_ORE_SLAB, "Nether Gold Ore Slab");
			builder.add(SSWPBlocks.NETHER_GOLD_ORE_STAIRS, "Nether Gold Ore Stairs");
			builder.add(SSWPBlocks.NETHER_GOLD_ORE_WALL, "Nether Gold Ore Wall");
			builder.add(SSWPBlocks.ANCIENT_DEBRIS_SLAB, "Ancient Debris Slab");
			builder.add(SSWPBlocks.ANCIENT_DEBRIS_STAIRS, "Ancient Debris Stairs");
			builder.add(SSWPBlocks.ANCIENT_DEBRIS_WALL, "Ancient Debris Wall");
			builder.add(SSWPBlocks.RAW_IRON_SLAB, "Raw Iron Slab");
			builder.add(SSWPBlocks.RAW_IRON_STAIRS, "Raw Iron Stairs");
			builder.add(SSWPBlocks.RAW_IRON_WALL, "Raw Iron Wall");
			builder.add(SSWPBlocks.RAW_COPPER_SLAB, "Raw Copper Slab");
			builder.add(SSWPBlocks.RAW_COPPER_STAIRS, "Raw Copper Stairs");
			builder.add(SSWPBlocks.RAW_COPPER_WALL, "Raw Copper Wall");
			builder.add(SSWPBlocks.RAW_GOLD_SLAB, "Raw Gold Slab");
			builder.add(SSWPBlocks.RAW_GOLD_STAIRS, "Raw Gold Stairs");
			builder.add(SSWPBlocks.RAW_GOLD_WALL, "Raw Gold Wall");
			builder.add(SSWPBlocks.GLOWSTONE_SLAB, "Glowstone Slab");
			builder.add(SSWPBlocks.GLOWSTONE_STAIRS, "Glowstone Stairs");
			builder.add(SSWPBlocks.GLOWSTONE_WALL, "Glowstone Wall");
			builder.add(SSWPBlocks.MANGROVE_ROOT_SLAB, "Mangrove Root Slab");
			builder.add(SSWPBlocks.MANGROVE_ROOT_STAIRS, "Mangrove Root Stairs");
			builder.add(SSWPBlocks.MANGROVE_ROOT_WALL, "Mangrove Root Wall");
			builder.add(SSWPBlocks.MANGROVE_ROOT_CARPET, "Mangrove Root Carpet");
			builder.add(SSWPBlocks.MUDDY_MANGROVE_ROOT_SLAB, "Muddy Mangrove Root Slab");
			builder.add(SSWPBlocks.MUDDY_MANGROVE_ROOT_STAIRS, "Muddy Mangrove Root Stairs");
			builder.add(SSWPBlocks.MUDDY_MANGROVE_ROOT_WALL, "Muddy Mangrove Root Wall");
			builder.add(SSWPBlocks.MUSHROOM_STEM_SLAB, "Mushroom Stem Slab");
			builder.add(SSWPBlocks.MUSHROOM_STEM_STAIRS, "Mushroom Stem Stairs");
			builder.add(SSWPBlocks.MUSHROOM_STEM_WALL, "Mushroom Stem Wall");
			builder.add(SSWPBlocks.OAK_LEAF_SLAB, "Oak Leaf Slab");
			builder.add(SSWPBlocks.OAK_LEAF_STAIRS, "Oak Leaf Stairs");
			builder.add(SSWPBlocks.OAK_LEAF_WALL, "Oak Leaf Hedge");
			builder.add(SSWPBlocks.OAK_LEAF_CARPET, "Oak Leaf Carpet");
			builder.add(SSWPBlocks.SPRUCE_LEAF_SLAB, "Spruce Leaf Slab");
			builder.add(SSWPBlocks.SPRUCE_LEAF_STAIRS, "Spruce Leaf Stairs");
			builder.add(SSWPBlocks.SPRUCE_LEAF_WALL, "Spruce Leaf Hedge");
			builder.add(SSWPBlocks.SPRUCE_LEAF_CARPET, "Spruce Leaf Carpet");
			builder.add(SSWPBlocks.BIRCH_LEAF_SLAB, "Birch Leaf Slab");
			builder.add(SSWPBlocks.BIRCH_LEAF_STAIRS, "Birch Leaf Stairs");
			builder.add(SSWPBlocks.BIRCH_LEAF_WALL, "Birch Leaf Hedge");
			builder.add(SSWPBlocks.BIRCH_LEAF_CARPET, "Birch Leaf Carpet");
			builder.add(SSWPBlocks.JUNGLE_LEAF_SLAB, "Jungle Leaf Slab");
			builder.add(SSWPBlocks.JUNGLE_LEAF_STAIRS, "Jungle Leaf Stairs");
			builder.add(SSWPBlocks.JUNGLE_LEAF_WALL, "Jungle Leaf Hedge");
			builder.add(SSWPBlocks.JUNGLE_LEAF_CARPET, "Jungle Leaf Carpet");
			builder.add(SSWPBlocks.ACACIA_LEAF_SLAB, "Acacia Leaf Slab");
			builder.add(SSWPBlocks.ACACIA_LEAF_STAIRS, "Acacia Leaf Stairs");
			builder.add(SSWPBlocks.ACACIA_LEAF_WALL, "Acacia Leaf Hedge");
			builder.add(SSWPBlocks.ACACIA_LEAF_CARPET, "Acacia Leaf Carpet");
			builder.add(SSWPBlocks.DARK_OAK_LEAF_SLAB, "Dark Oak Leaf Slab");
			builder.add(SSWPBlocks.DARK_OAK_LEAF_STAIRS, "Dark Oak Leaf Stairs");
			builder.add(SSWPBlocks.DARK_OAK_LEAF_WALL, "Dark Oak Leaf Hedge");
			builder.add(SSWPBlocks.DARK_OAK_LEAF_CARPET, "Dark Oak Leaf Carpet");
			builder.add(SSWPBlocks.MANGROVE_LEAF_SLAB, "Mangrove Leaf Slab");
			builder.add(SSWPBlocks.MANGROVE_LEAF_STAIRS, "Mangrove Leaf Stairs");
			builder.add(SSWPBlocks.MANGROVE_LEAF_WALL, "Mangrove Leaf Hedge");
			builder.add(SSWPBlocks.MANGROVE_LEAF_CARPET, "Mangrove Leaf Carpet");
			builder.add(SSWPBlocks.CHERRY_LEAF_SLAB, "Cherry Leaf Slab");
			builder.add(SSWPBlocks.CHERRY_LEAF_STAIRS, "Cherry Leaf Stairs");
			builder.add(SSWPBlocks.CHERRY_LEAF_WALL, "Cherry Leaf Hedge");
			builder.add(SSWPBlocks.CHERRY_LEAF_CARPET, "Cherry Leaf Carpet");
			builder.add(SSWPBlocks.AZALEA_LEAF_SLAB, "Azalea Leaf Slab");
			builder.add(SSWPBlocks.AZALEA_LEAF_STAIRS, "Azalea Leaf Stairs");
			builder.add(SSWPBlocks.AZALEA_LEAF_WALL, "Azalea Leaf Hedge");
			builder.add(SSWPBlocks.AZALEA_LEAF_CARPET, "Azalea Leaf Carpet");
			builder.add(SSWPBlocks.FLOWERING_AZALEA_LEAF_SLAB, "Flowering Azalea Leaf Slab");
			builder.add(SSWPBlocks.FLOWERING_AZALEA_LEAF_STAIRS, "Flowering Azalea Leaf Stairs");
			builder.add(SSWPBlocks.FLOWERING_AZALEA_LEAF_WALL, "Flowering Azalea Leaf Hedge");
			builder.add(SSWPBlocks.FLOWERING_AZALEA_LEAF_CARPET, "Flowering Azalea Leaf Carpet");
			builder.add(SSWPBlocks.BROWN_MUSHROOM_SLAB, "Brown Mushroom Slab");
			builder.add(SSWPBlocks.BROWN_MUSHROOM_STAIRS, "Brown Mushroom Stairs");
			builder.add(SSWPBlocks.BROWN_MUSHROOM_WALL, "Brown Mushroom Wall");
			builder.add(SSWPBlocks.RED_MUSHROOM_SLAB, "Red Mushroom Slab");
			builder.add(SSWPBlocks.RED_MUSHROOM_STAIRS, "Red Mushroom Stairs");
			builder.add(SSWPBlocks.RED_MUSHROOM_WALL, "Red Mushroom Wall");
			builder.add(SSWPBlocks.NETHER_WART_SLAB, "Nether Wart Slab");
			builder.add(SSWPBlocks.NETHER_WART_STAIRS, "Nether Wart Stairs");
			builder.add(SSWPBlocks.NETHER_WART_WALL, "Nether Wart Wall");
			builder.add(SSWPBlocks.WARPED_WART_SLAB, "Warped Wart Slab");
			builder.add(SSWPBlocks.WARPED_WART_STAIRS, "Warped Wart Stairs");
			builder.add(SSWPBlocks.WARPED_WART_WALL, "Warped Wart Wall");
			builder.add(SSWPBlocks.SHROOMLIGHT_SLAB, "Shroomlight Slab");
			builder.add(SSWPBlocks.SHROOMLIGHT_STAIRS, "Shroomlight Stairs");
			builder.add(SSWPBlocks.SHROOMLIGHT_WALL, "Shroomlight Wall");
			builder.add(SSWPBlocks.DRIED_KELP_SLAB, "Dried Kelp Slab");
			builder.add(SSWPBlocks.DRIED_KELP_STAIRS, "Dried Kelp Stairs");
			builder.add(SSWPBlocks.DRIED_KELP_WALL, "Dried Kelp Wall");
			builder.add(SSWPBlocks.TUBE_CORAL_SLAB, "Tube Coral Slab");
			builder.add(SSWPBlocks.TUBE_CORAL_STAIRS, "Tube Coral Stairs");
			builder.add(SSWPBlocks.TUBE_CORAL_WALL, "Tube Coral Wall");
			builder.add(SSWPBlocks.BRAIN_CORAL_SLAB, "Brain Coral Slab");
			builder.add(SSWPBlocks.BRAIN_CORAL_STAIRS, "Brain Coral Stairs");
			builder.add(SSWPBlocks.BRAIN_CORAL_WALL, "Brain Coral Wall");
			builder.add(SSWPBlocks.BUBBLE_CORAL_SLAB, "Bubble Coral Slab");
			builder.add(SSWPBlocks.BUBBLE_CORAL_STAIRS, "Bubble Coral Stairs");
			builder.add(SSWPBlocks.BUBBLE_CORAL_WALL, "Bubble Coral Wall");
			builder.add(SSWPBlocks.FIRE_CORAL_SLAB, "Fire Coral Slab");
			builder.add(SSWPBlocks.FIRE_CORAL_STAIRS, "Fire Coral Stairs");
			builder.add(SSWPBlocks.FIRE_CORAL_WALL, "Fire Coral Wall");
			builder.add(SSWPBlocks.HORN_CORAL_SLAB, "Horn Coral Slab");
			builder.add(SSWPBlocks.HORN_CORAL_STAIRS, "Horn Coral Stairs");
			builder.add(SSWPBlocks.HORN_CORAL_WALL, "Horn Coral Wall");
			builder.add(SSWPBlocks.DEAD_TUBE_CORAL_SLAB, "Dead Tube Coral Slab");
			builder.add(SSWPBlocks.DEAD_TUBE_CORAL_STAIRS, "Dead Tube Coral Stairs");
			builder.add(SSWPBlocks.DEAD_TUBE_CORAL_WALL, "Dead Tube Coral Wall");
			builder.add(SSWPBlocks.DEAD_BRAIN_CORAL_SLAB, "Dead Brain Coral Slab");
			builder.add(SSWPBlocks.DEAD_BRAIN_CORAL_STAIRS, "Dead Brain Coral Stairs");
			builder.add(SSWPBlocks.DEAD_BRAIN_CORAL_WALL, "Dead Brain Coral Wall");
			builder.add(SSWPBlocks.DEAD_BUBBLE_CORAL_SLAB, "Dead Bubble Coral Slab");
			builder.add(SSWPBlocks.DEAD_BUBBLE_CORAL_STAIRS, "Dead Bubble Coral Stairs");
			builder.add(SSWPBlocks.DEAD_BUBBLE_CORAL_WALL, "Dead Bubble Coral Wall");
			builder.add(SSWPBlocks.DEAD_FIRE_CORAL_SLAB, "Dead Fire Coral Slab");
			builder.add(SSWPBlocks.DEAD_FIRE_CORAL_STAIRS, "Dead Fire Coral Stairs");
			builder.add(SSWPBlocks.DEAD_FIRE_CORAL_WALL, "Dead Fire Coral Wall");
			builder.add(SSWPBlocks.DEAD_HORN_CORAL_SLAB, "Dead Horn Coral Slab");
			builder.add(SSWPBlocks.DEAD_HORN_CORAL_STAIRS, "Dead Horn Coral Stairs");
			builder.add(SSWPBlocks.DEAD_HORN_CORAL_WALL, "Dead Horn Coral Wall");
			builder.add(SSWPBlocks.HAY_SLAB, "Hay Slab");
			builder.add(SSWPBlocks.HAY_STAIRS, "Hay Stairs");
			builder.add(SSWPBlocks.HAY_WALL, "Hay Wall");
			builder.add(SSWPBlocks.HONEYCOMB_SLAB, "Honeycomb Slab");
			builder.add(SSWPBlocks.HONEYCOMB_STAIRS, "Honeycomb Stairs");
			builder.add(SSWPBlocks.HONEYCOMB_WALL, "Honeycomb Wall");
			builder.add(SSWPBlocks.OCHRE_FROGLIGHT_SLAB, "Ochre Froglight Slab");
			builder.add(SSWPBlocks.OCHRE_FROGLIGHT_STAIRS, "Ochre Froglight Stairs");
			builder.add(SSWPBlocks.OCHRE_FROGLIGHT_WALL, "Ochre Froglight Wall");
			builder.add(SSWPBlocks.VERDANT_FROGLIGHT_SLAB, "Verdant Froglight Slab");
			builder.add(SSWPBlocks.VERDANT_FROGLIGHT_STAIRS, "Verdant Froglight Stairs");
			builder.add(SSWPBlocks.VERDANT_FROGLIGHT_WALL, "Verdant Froglight Wall");
			builder.add(SSWPBlocks.PEARLESCENT_FROGLIGHT_SLAB, "Pearlescent Froglight Slab");
			builder.add(SSWPBlocks.PEARLESCENT_FROGLIGHT_STAIRS, "Pearlescent Froglight Stairs");
			builder.add(SSWPBlocks.PEARLESCENT_FROGLIGHT_WALL, "Pearlescent Froglight Wall");
			builder.add(SSWPBlocks.SCULK_SLAB, "Sculk Slab");
			builder.add(SSWPBlocks.SCULK_STAIRS, "Sculk Stairs");
			builder.add(SSWPBlocks.SCULK_WALL, "Sculk Wall");
			builder.add(SSWPBlocks.BEDROCK_SLAB, "Bedrock Slab");
			builder.add(SSWPBlocks.BEDROCK_STAIRS, "Bedrock Stairs");
			builder.add(SSWPBlocks.BEDROCK_WALL, "Bedrock Wall");
			builder.add(SSWPBlocks.REDSTONE_LAMP_SLAB, "Redstone Lamp Slab");
			builder.add(SSWPBlocks.REDSTONE_LAMP_STAIRS, "Redstone Lamp Stairs");
			builder.add(SSWPBlocks.REDSTONE_LAMP_WALL, "Redstone Lamp Wall");
			builder.add(SSWPBlocks.INFESTED_MOSSY_COBBLESTONE, "Infested Mossy Cobblestone");
			builder.add(SSWPBlocks.INFESTED_SMOOTH_STONE, "Infested Smooth Stone");
			builder.add(SSWPBlocks.INFESTED_GRANITE, "Infested Granite");
			builder.add(SSWPBlocks.INFESTED_POLISHED_GRANITE, "Infested Polished Granite");
			builder.add(SSWPBlocks.INFESTED_DIORITE, "Infested Diorite");
			builder.add(SSWPBlocks.INFESTED_POLISHED_DIORITE, "Infested Polished Diorite");
			builder.add(SSWPBlocks.INFESTED_ANDESITE, "Infested Andesite");
			builder.add(SSWPBlocks.INFESTED_POLISHED_ANDESITE, "Infested Polished Andesite");
			builder.add(SSWPBlocks.INFESTED_COBBLED_DEEPSLATE, "Infested Cobbled Deepslate");
			builder.add(SSWPBlocks.INFESTED_CHISELED_DEEPSLATE, "Infested Chiseled Deepslate");
			builder.add(SSWPBlocks.INFESTED_POLISHED_DEEPSLATE, "Infested Polished Deepslate");
			builder.add(SSWPBlocks.INFESTED_DEEPSLATE_BRICKS, "Infested Deepslate Bricks");
			builder.add(SSWPBlocks.INFESTED_CRACKED_DEEPSLATE_BRICKS, "Infested Cracked Deepslate Bricks");
			builder.add(SSWPBlocks.INFESTED_DEEPSLATE_TILES, "Infested Deepslate Tiles");
			builder.add(SSWPBlocks.INFESTED_CRACKED_DEEPSLATE_TILES, "Infested Cracked Deepslate Tiles");
			builder.add(SSWPBlocks.INFESTED_TUFF, "Infested Tuff");
			builder.add(SSWPBlocks.INFESTED_CHISELED_TUFF, "Infested Chiseled Tuff");
			builder.add(SSWPBlocks.INFESTED_POLISHED_TUFF, "Infested Polished Tuff");
			builder.add(SSWPBlocks.INFESTED_TUFF_BRICKS, "Infested Tuff Bricks");
			builder.add(SSWPBlocks.INFESTED_CHISELED_TUFF_BRICKS, "Infested Chiseled Tuff Bricks");
			builder.add(SSWPBlocks.INFESTED_CALCITE, "Infested Calcite");
			builder.add(SSWPBlocks.INFESTED_DRIPSTONE_BLOCK, "Infested Dripstone Block");
			builder.add(SSWPBlocks.OAK_LADDER, "Oak Ladder");
			builder.add(SSWPBlocks.SPRUCE_LADDER, "Spruce Ladder");
			builder.add(SSWPBlocks.BIRCH_LADDER, "Birch Ladder");
			builder.add(SSWPBlocks.JUNGLE_LADDER, "Jungle Ladder");
			builder.add(SSWPBlocks.ACACIA_LADDER, "Acacia Ladder");
			builder.add(SSWPBlocks.DARK_OAK_LADDER, "Dark Oak Ladder");
			builder.add(SSWPBlocks.MANGROVE_LADDER, "Mangrove Ladder");
			builder.add(SSWPBlocks.CHERRY_LADDER, "Cherry Ladder");
			builder.add(SSWPBlocks.BAMBOO_LADDER, "Bamboo Ladder");
			builder.add(SSWPBlocks.CRIMSON_LADDER, "Crimson Ladder");
			builder.add(SSWPBlocks.WARPED_LADDER, "Warped Ladder");
			builder.add(SSWPBlocks.IRON_LADDER, "Iron Ladder");
			builder.add(SSWPBlocks.GOLD_LADDER, "Gold Ladder");
			builder.add(SSWPBlocks.NETHERITE_LADDER, "Netherite Ladder");
			builder.add(SSWPBlocks.COPPER_LADDER, "Copper Ladder");
			builder.add(SSWPBlocks.EXPOSED_COPPER_LADDER, "Exposed Copper Ladder");
			builder.add(SSWPBlocks.WEATHERED_COPPER_LADDER, "Weathered Copper Ladder");
			builder.add(SSWPBlocks.OXIDIZED_COPPER_LADDER, "Oxidized Copper Ladder");
			builder.add(SSWPBlocks.WAXED_COPPER_LADDER, "Waxed Copper Ladder");
			builder.add(SSWPBlocks.WAXED_EXPOSED_COPPER_LADDER, "Waxed Exposed Copper Ladder");
			builder.add(SSWPBlocks.WAXED_WEATHERED_COPPER_LADDER, "Waxed Weathered Copper Ladder");
			builder.add(SSWPBlocks.WAXED_OXIDIZED_COPPER_LADDER, "Waxed Oxidized Copper Ladder");
			builder.add(SSWPBlocks.IRON_SIGN, "Iron Sign");
			builder.add(SSWPBlocks.IRON_HANGING_SIGN, "Iron Hanging Sign");
			builder.add(SSWPBlocks.GOLD_SIGN, "Gold Sign");
			builder.add(SSWPBlocks.GOLD_HANGING_SIGN, "Gold Hanging Sign");
			builder.add(SSWPBlocks.NETHERITE_SIGN, "Netherite Sign");
			builder.add(SSWPBlocks.NETHERITE_HANGING_SIGN, "Netherite Hanging Sign");
			builder.add(SSWPBlocks.COPPER_SIGN, "Copper Sign");
			builder.add(SSWPBlocks.COPPER_HANGING_SIGN, "Copper Hanging Sign");
			builder.add(SSWPBlocks.EXPOSED_COPPER_SIGN, "Exposed Copper Sign");
			builder.add(SSWPBlocks.EXPOSED_COPPER_HANGING_SIGN, "Exposed Copper Hanging Sign");
			builder.add(SSWPBlocks.WEATHERED_COPPER_SIGN, "Weathered Copper Sign");
			builder.add(SSWPBlocks.WEATHERED_COPPER_HANGING_SIGN, "Weathered Copper Hanging Sign");
			builder.add(SSWPBlocks.OXIDIZED_COPPER_SIGN, "Oxidized Copper Sign");
			builder.add(SSWPBlocks.OXIDIZED_COPPER_HANGING_SIGN, "Oxidized Copper Hanging Sign");
			builder.add(SSWPBlocks.WAXED_COPPER_SIGN, "Waxed Copper Sign");
			builder.add(SSWPBlocks.WAXED_COPPER_HANGING_SIGN, "Waxed Copper Hanging Sign");
			builder.add(SSWPBlocks.WAXED_EXPOSED_COPPER_SIGN, "Waxed Exposed Copper Sign");
			builder.add(SSWPBlocks.WAXED_EXPOSED_COPPER_HANGING_SIGN, "Waxed Exposed Copper Hanging Sign");
			builder.add(SSWPBlocks.WAXED_WEATHERED_COPPER_SIGN, "Waxed Weathered Copper Sign");
			builder.add(SSWPBlocks.WAXED_WEATHERED_COPPER_HANGING_SIGN, "Waxed Weathered Copper Hanging Sign");
			builder.add(SSWPBlocks.WAXED_OXIDIZED_COPPER_SIGN, "Waxed Oxidized Copper Sign");
			builder.add(SSWPBlocks.WAXED_OXIDIZED_COPPER_HANGING_SIGN, "Waxed Oxidized Copper Hanging Sign");
			builder.add(SSWPBlocks.OAK_BOOKSHELF, "Oak Bookshelf");
			builder.add(SSWPBlocks.SPRUCE_BOOKSHELF, "Spruce Bookshelf");
			builder.add(SSWPBlocks.BIRCH_BOOKSHELF, "Birch Bookshelf");
			builder.add(SSWPBlocks.JUNGLE_BOOKSHELF, "Jungle Bookshelf");
			builder.add(SSWPBlocks.ACACIA_BOOKSHELF, "Acacia Bookshelf");
			builder.add(SSWPBlocks.DARK_OAK_BOOKSHELF, "Dark Oak Bookshelf");
			builder.add(SSWPBlocks.MANGROVE_BOOKSHELF, "Mangrove Bookshelf");
			builder.add(SSWPBlocks.CHERRY_BOOKSHELF, "Cherry Bookshelf");
			builder.add(SSWPBlocks.BAMBOO_BOOKSHELF, "Bamboo Bookshelf");
			builder.add(SSWPBlocks.CRIMSON_BOOKSHELF, "Crimson Bookshelf");
			builder.add(SSWPBlocks.WARPED_BOOKSHELF, "Warped Bookshelf");
			builder.add(SSWPBlocks.OAK_CRAFTING_TABLE, "Oak Crafting Table");
			builder.add(SSWPBlocks.SPRUCE_CRAFTING_TABLE, "Spruce Crafting Table");
			builder.add(SSWPBlocks.BIRCH_CRAFTING_TABLE, "Birch Crafting Table");
			builder.add(SSWPBlocks.JUNGLE_CRAFTING_TABLE, "Jungle Crafting Table");
			builder.add(SSWPBlocks.ACACIA_CRAFTING_TABLE, "Acacia Crafting Table");
			builder.add(SSWPBlocks.DARK_OAK_CRAFTING_TABLE, "Dark Oak Crafting Table");
			builder.add(SSWPBlocks.MANGROVE_CRAFTING_TABLE, "Mangrove Crafting Table");
			builder.add(SSWPBlocks.CHERRY_CRAFTING_TABLE, "Cherry Crafting Table");
			builder.add(SSWPBlocks.BAMBOO_CRAFTING_TABLE, "Bamboo Crafting Table");
			builder.add(SSWPBlocks.CRIMSON_CRAFTING_TABLE, "Crimson Crafting Table");
			builder.add(SSWPBlocks.WARPED_CRAFTING_TABLE, "Warped Crafting Table");
			builder.add(SSWPBlocks.OAK_LOOM, "Oak Loom");
			builder.add(SSWPBlocks.SPRUCE_LOOM, "Spruce Loom");
			builder.add(SSWPBlocks.BIRCH_LOOM, "Birch Loom");
			builder.add(SSWPBlocks.JUNGLE_LOOM, "Jungle Loom");
			builder.add(SSWPBlocks.ACACIA_LOOM, "Acacia Loom");
			builder.add(SSWPBlocks.DARK_OAK_LOOM, "Dark Oak Loom");
			builder.add(SSWPBlocks.MANGROVE_LOOM, "Mangrove Loom");
			builder.add(SSWPBlocks.CHERRY_LOOM, "Cherry Loom");
			builder.add(SSWPBlocks.BAMBOO_LOOM, "Bamboo Loom");
			builder.add(SSWPBlocks.CRIMSON_LOOM, "Crimson Loom");
			builder.add(SSWPBlocks.WARPED_LOOM, "Warped Loom");
			builder.add(SSWPBlocks.OAK_CARTOGRAPHY_TABLE, "Oak Cartography Table");
			builder.add(SSWPBlocks.SPRUCE_CARTOGRAPHY_TABLE, "Spruce Cartography Table");
			builder.add(SSWPBlocks.BIRCH_CARTOGRAPHY_TABLE, "Birch Cartography Table");
			builder.add(SSWPBlocks.JUNGLE_CARTOGRAPHY_TABLE, "Jungle Cartography Table");
			builder.add(SSWPBlocks.ACACIA_CARTOGRAPHY_TABLE, "Acacia Cartography Table");
			builder.add(SSWPBlocks.DARK_OAK_CARTOGRAPHY_TABLE, "Dark Oak Cartography Table");
			builder.add(SSWPBlocks.MANGROVE_CARTOGRAPHY_TABLE, "Mangrove Cartography Table");
			builder.add(SSWPBlocks.CHERRY_CARTOGRAPHY_TABLE, "Cherry Cartography Table");
			builder.add(SSWPBlocks.BAMBOO_CARTOGRAPHY_TABLE, "Bamboo Cartography Table");
			builder.add(SSWPBlocks.CRIMSON_CARTOGRAPHY_TABLE, "Crimson Cartography Table");
			builder.add(SSWPBlocks.WARPED_CARTOGRAPHY_TABLE, "Warped Cartography Table");
			builder.add(SSWPBlocks.OAK_FLETCHING_TABLE, "Oak Fletching Table");
			builder.add(SSWPBlocks.SPRUCE_FLETCHING_TABLE, "Spruce Fletching Table");
			builder.add(SSWPBlocks.BIRCH_FLETCHING_TABLE, "Birch Fletching Table");
			builder.add(SSWPBlocks.JUNGLE_FLETCHING_TABLE, "Jungle Fletching Table");
			builder.add(SSWPBlocks.ACACIA_FLETCHING_TABLE, "Acacia Fletching Table");
			builder.add(SSWPBlocks.DARK_OAK_FLETCHING_TABLE, "Dark Oak Fletching Table");
			builder.add(SSWPBlocks.MANGROVE_FLETCHING_TABLE, "Mangrove Fletching Table");
			builder.add(SSWPBlocks.CHERRY_FLETCHING_TABLE, "Cherry Fletching Table");
			builder.add(SSWPBlocks.BAMBOO_FLETCHING_TABLE, "Bamboo Fletching Table");
			builder.add(SSWPBlocks.CRIMSON_FLETCHING_TABLE, "Crimson Fletching Table");
			builder.add(SSWPBlocks.WARPED_FLETCHING_TABLE, "Warped Fletching Table");
			builder.add(SSWPBlocks.OAK_SMITHING_TABLE, "Oak Smithing Table");
			builder.add(SSWPBlocks.SPRUCE_SMITHING_TABLE, "Spruce Smithing Table");
			builder.add(SSWPBlocks.BIRCH_SMITHING_TABLE, "Birch Smithing Table");
			builder.add(SSWPBlocks.JUNGLE_SMITHING_TABLE, "Jungle Smithing Table");
			builder.add(SSWPBlocks.ACACIA_SMITHING_TABLE, "Acacia Smithing Table");
			builder.add(SSWPBlocks.DARK_OAK_SMITHING_TABLE, "Dark Oak Smithing Table");
			builder.add(SSWPBlocks.MANGROVE_SMITHING_TABLE, "Mangrove Smithing Table");
			builder.add(SSWPBlocks.CHERRY_SMITHING_TABLE, "Cherry Smithing Table");
			builder.add(SSWPBlocks.BAMBOO_SMITHING_TABLE, "Bamboo Smithing Table");
			builder.add(SSWPBlocks.CRIMSON_SMITHING_TABLE, "Crimson Smithing Table");
			builder.add(SSWPBlocks.WARPED_SMITHING_TABLE, "Warped Smithing Table");
			builder.add(SSWPBlocks.OAK_COMPOSTER, "Oak Composter");
			builder.add(SSWPBlocks.SPRUCE_COMPOSTER, "Spruce Composter");
			builder.add(SSWPBlocks.BIRCH_COMPOSTER, "Birch Composter");
			builder.add(SSWPBlocks.JUNGLE_COMPOSTER, "Jungle Composter");
			builder.add(SSWPBlocks.ACACIA_COMPOSTER, "Acacia Composter");
			builder.add(SSWPBlocks.DARK_OAK_COMPOSTER, "Dark Oak Composter");
			builder.add(SSWPBlocks.MANGROVE_COMPOSTER, "Mangrove Composter");
			builder.add(SSWPBlocks.CHERRY_COMPOSTER, "Cherry Composter");
			builder.add(SSWPBlocks.BAMBOO_COMPOSTER, "Bamboo Composter");
			builder.add(SSWPBlocks.CRIMSON_COMPOSTER, "Crimson Composter");
			builder.add(SSWPBlocks.WARPED_COMPOSTER, "Warped Composter");
			builder.add(SSWPBlocks.OAK_LECTERN, "Oak Lectern");
			builder.add(SSWPBlocks.SPRUCE_LECTERN, "Spruce Lectern");
			builder.add(SSWPBlocks.BIRCH_LECTERN, "Birch Lectern");
			builder.add(SSWPBlocks.JUNGLE_LECTERN, "Jungle Lectern");
			builder.add(SSWPBlocks.ACACIA_LECTERN, "Acacia Lectern");
			builder.add(SSWPBlocks.DARK_OAK_LECTERN, "Dark Oak Lectern");
			builder.add(SSWPBlocks.MANGROVE_LECTERN, "Mangrove Lectern");
			builder.add(SSWPBlocks.CHERRY_LECTERN, "Cherry Lectern");
			builder.add(SSWPBlocks.BAMBOO_LECTERN, "Bamboo Lectern");
			builder.add(SSWPBlocks.CRIMSON_LECTERN, "Crimson Lectern");
			builder.add(SSWPBlocks.WARPED_LECTERN, "Warped Lectern");
			builder.add(SSWPBlocks.OAK_BARREL, "Oak Barrel");
			builder.add(SSWPBlocks.SPRUCE_BARREL, "Spruce Barrel");
			builder.add(SSWPBlocks.BIRCH_BARREL, "Birch Barrel");
			builder.add(SSWPBlocks.JUNGLE_BARREL, "Jungle Barrel");
			builder.add(SSWPBlocks.ACACIA_BARREL, "Acacia Barrel");
			builder.add(SSWPBlocks.DARK_OAK_BARREL, "Dark Oak Barrel");
			builder.add(SSWPBlocks.MANGROVE_BARREL, "Mangrove Barrel");
			builder.add(SSWPBlocks.CHERRY_BARREL, "Cherry Barrel");
			builder.add(SSWPBlocks.BAMBOO_BARREL, "Bamboo Barrel");
			builder.add(SSWPBlocks.CRIMSON_BARREL, "Crimson Barrel");
			builder.add(SSWPBlocks.WARPED_BARREL, "Warped Barrel");
			builder.add(SSWPBlocks.OAK_TRIPWIRE_HOOK, "Oak Tripwire Hook");
			builder.add(SSWPBlocks.SPRUCE_TRIPWIRE_HOOK, "Spruce Tripwire Hook");
			builder.add(SSWPBlocks.BIRCH_TRIPWIRE_HOOK, "Birch Tripwire Hook");
			builder.add(SSWPBlocks.JUNGLE_TRIPWIRE_HOOK, "Jungle Tripwire Hook");
			builder.add(SSWPBlocks.ACACIA_TRIPWIRE_HOOK, "Acacia Tripwire Hook");
			builder.add(SSWPBlocks.DARK_OAK_TRIPWIRE_HOOK, "Dark Oak Tripwire Hook");
			builder.add(SSWPBlocks.MANGROVE_TRIPWIRE_HOOK, "Mangrove Tripwire Hook");
			builder.add(SSWPBlocks.CHERRY_TRIPWIRE_HOOK, "Cherry Tripwire Hook");
			builder.add(SSWPBlocks.BAMBOO_TRIPWIRE_HOOK, "Bamboo Tripwire Hook");
			builder.add(SSWPBlocks.CRIMSON_TRIPWIRE_HOOK, "Crimson Tripwire Hook");
			builder.add(SSWPBlocks.WARPED_TRIPWIRE_HOOK, "Warped Tripwire Hook");
			builder.add(SSWPBlocks.OAK_BEEHIVE, "Oak Beehive");
			builder.add(SSWPBlocks.SPRUCE_BEEHIVE, "Spruce Beehive");
			builder.add(SSWPBlocks.BIRCH_BEEHIVE, "Birch Beehive");
			builder.add(SSWPBlocks.JUNGLE_BEEHIVE, "Jungle Beehive");
			builder.add(SSWPBlocks.ACACIA_BEEHIVE, "Acacia Beehive");
			builder.add(SSWPBlocks.DARK_OAK_BEEHIVE, "Dark Oak Beehive");
			builder.add(SSWPBlocks.MANGROVE_BEEHIVE, "Mangrove Beehive");
			builder.add(SSWPBlocks.CHERRY_BEEHIVE, "Cherry Beehive");
			builder.add(SSWPBlocks.BAMBOO_BEEHIVE, "Bamboo Beehive");
			builder.add(SSWPBlocks.CRIMSON_BEEHIVE, "Crimson Beehive");
			builder.add(SSWPBlocks.WARPED_BEEHIVE, "Warped Beehive");
			builder.add(SSWPBlocks.OAK_CHISELED_BOOKSHELF, "Oak Chiseled Bookshelf");
			builder.add(SSWPBlocks.SPRUCE_CHISELED_BOOKSHELF, "Spruce Chiseled Bookshelf");
			builder.add(SSWPBlocks.BIRCH_CHISELED_BOOKSHELF, "Birch Chiseled Bookshelf");
			builder.add(SSWPBlocks.JUNGLE_CHISELED_BOOKSHELF, "Jungle Chiseled Bookshelf");
			builder.add(SSWPBlocks.ACACIA_CHISELED_BOOKSHELF, "Acacia Chiseled Bookshelf");
			builder.add(SSWPBlocks.DARK_OAK_CHISELED_BOOKSHELF, "Dark Oak Chiseled Bookshelf");
			builder.add(SSWPBlocks.MANGROVE_CHISELED_BOOKSHELF, "Mangrove Chiseled Bookshelf");
			builder.add(SSWPBlocks.CHERRY_CHISELED_BOOKSHELF, "Cherry Chiseled Bookshelf");
			builder.add(SSWPBlocks.BAMBOO_CHISELED_BOOKSHELF, "Bamboo Chiseled Bookshelf");
			builder.add(SSWPBlocks.CRIMSON_CHISELED_BOOKSHELF, "Crimson Chiseled Bookshelf");
			builder.add(SSWPBlocks.WARPED_CHISELED_BOOKSHELF, "Warped Chiseled Bookshelf");
			builder.add(SSWPBlocks.OAK_CHEST, "Oak Chest");
			builder.add(SSWPBlocks.SPRUCE_CHEST, "Spruce Chest");
			builder.add(SSWPBlocks.BIRCH_CHEST, "Birch Chest");
			builder.add(SSWPBlocks.JUNGLE_CHEST, "Jungle Chest");
			builder.add(SSWPBlocks.ACACIA_CHEST, "Acacia Chest");
			builder.add(SSWPBlocks.DARK_OAK_CHEST, "Dark Oak Chest");
			builder.add(SSWPBlocks.MANGROVE_CHEST, "Mangrove Chest");
			builder.add(SSWPBlocks.CHERRY_CHEST, "Cherry Chest");
			builder.add(SSWPBlocks.BAMBOO_CHEST, "Bamboo Chest");
			builder.add(SSWPBlocks.CRIMSON_CHEST, "Crimson Chest");
			builder.add(SSWPBlocks.WARPED_CHEST, "Warped Chest");
			builder.add(SSWPBlocks.OAK_TRAPPED_CHEST, "Oak Trapped Chest");
			builder.add(SSWPBlocks.SPRUCE_TRAPPED_CHEST, "Spruce Trapped Chest");
			builder.add(SSWPBlocks.BIRCH_TRAPPED_CHEST, "Birch Trapped Chest");
			builder.add(SSWPBlocks.JUNGLE_TRAPPED_CHEST, "Jungle Trapped Chest");
			builder.add(SSWPBlocks.ACACIA_TRAPPED_CHEST, "Acacia Trapped Chest");
			builder.add(SSWPBlocks.DARK_OAK_TRAPPED_CHEST, "Dark Oak Trapped Chest");
			builder.add(SSWPBlocks.MANGROVE_TRAPPED_CHEST, "Mangrove Trapped Chest");
			builder.add(SSWPBlocks.CHERRY_TRAPPED_CHEST, "Cherry Trapped Chest");
			builder.add(SSWPBlocks.BAMBOO_TRAPPED_CHEST, "Bamboo Trapped Chest");
			builder.add(SSWPBlocks.CRIMSON_TRAPPED_CHEST, "Crimson Trapped Chest");
			builder.add(SSWPBlocks.WARPED_TRAPPED_CHEST, "Warped Trapped Chest");
			builder.add(Blocks.CAULDRON, "Iron Cauldron");
			builder.add(SSWPBlocks.GOLD_CAULDRON, "Gold Cauldron");
			builder.add(SSWPBlocks.NETHERITE_CAULDRON, "Netherite Cauldron");
			builder.add(SSWPBlocks.COPPER_CAULDRON, "Copper Cauldron");
			builder.add(SSWPBlocks.EXPOSED_COPPER_CAULDRON, "Exposed Copper Cauldron");
			builder.add(SSWPBlocks.WEATHERED_COPPER_CAULDRON, "Weathered Copper Cauldron");
			builder.add(SSWPBlocks.OXIDIZED_COPPER_CAULDRON, "Oxidized Copper Cauldron");
			builder.add(SSWPBlocks.WAXED_COPPER_CAULDRON, "Waxed Copper Cauldron");
			builder.add(SSWPBlocks.WAXED_EXPOSED_COPPER_CAULDRON, "Waxed Exposed Copper Cauldron");
			builder.add(SSWPBlocks.WAXED_WEATHERED_COPPER_CAULDRON, "Waxed Weathered Copper Cauldron");
			builder.add(SSWPBlocks.WAXED_OXIDIZED_COPPER_CAULDRON, "Waxed Oxidized Copper Cauldron");
			builder.add(Blocks.LANTERN, "Iron Lantern");
			builder.add(Blocks.SOUL_LANTERN, "Iron Soul Lantern");
			builder.add(SSWPBlocks.GOLD_LANTERN, "Gold Lantern");
			builder.add(SSWPBlocks.GOLD_SOUL_LANTERN, "Gold Soul Lantern");
			builder.add(SSWPBlocks.NETHERITE_LANTERN, "Netherite Lantern");
			builder.add(SSWPBlocks.NETHERITE_SOUL_LANTERN, "Netherite Soul Lantern");
			builder.add(SSWPBlocks.COPPER_LANTERN, "Copper Lantern");
			builder.add(SSWPBlocks.COPPER_SOUL_LANTERN, "Copper Soul Lantern");
			builder.add(SSWPBlocks.EXPOSED_COPPER_LANTERN, "Exposed Copper Lantern");
			builder.add(SSWPBlocks.EXPOSED_COPPER_SOUL_LANTERN, "Exposed Copper Soul Lantern");
			builder.add(SSWPBlocks.WEATHERED_COPPER_LANTERN, "Weathered Copper Lantern");
			builder.add(SSWPBlocks.WEATHERED_COPPER_SOUL_LANTERN, "Weathered Copper Soul Lantern");
			builder.add(SSWPBlocks.OXIDIZED_COPPER_LANTERN, "Oxidized Copper Lantern");
			builder.add(SSWPBlocks.OXIDIZED_COPPER_SOUL_LANTERN, "Oxidized Copper Soul Lantern");
			builder.add(SSWPBlocks.WAXED_COPPER_LANTERN, "Waxed Copper Lantern");
			builder.add(SSWPBlocks.WAXED_COPPER_SOUL_LANTERN, "Waxed Copper Soul Lantern");
			builder.add(SSWPBlocks.WAXED_EXPOSED_COPPER_LANTERN, "Waxed Exposed Copper Lantern");
			builder.add(SSWPBlocks.WAXED_EXPOSED_COPPER_SOUL_LANTERN, "Waxed Exposed Copper Soul Lantern");
			builder.add(SSWPBlocks.WAXED_WEATHERED_COPPER_LANTERN, "Waxed Weathered Copper Lantern");
			builder.add(SSWPBlocks.WAXED_WEATHERED_COPPER_SOUL_LANTERN, "Waxed Weathered Copper Soul Lantern");
			builder.add(SSWPBlocks.WAXED_OXIDIZED_COPPER_LANTERN, "Waxed Oxidized Copper Lantern");
			builder.add(SSWPBlocks.WAXED_OXIDIZED_COPPER_SOUL_LANTERN, "Waxed Oxidized Copper Soul Lantern");
			builder.add(SSWPBlocks.NETHERITE_ANVIL, "Netherite Anvil");
			
			builder.add(SSWPItems.RED_NETHER_BRICK, "Red Nether Brick");
			builder.add(SSWPItems.COPPER_NUGGET, "Copper Nugget");
			builder.add(SSWPItems.NETHERITE_NUGGET, "Netherite Nugget");
			builder.add(SSWPItems.OAK_STICK, "Oak Stick");
			builder.add(SSWPItems.SPRUCE_STICK, "Spruce Stick");
			builder.add(SSWPItems.BIRCH_STICK, "Birch Stick");
			builder.add(SSWPItems.JUNGLE_STICK, "Jungle Stick");
			builder.add(SSWPItems.ACACIA_STICK, "Acacia Stick");
			builder.add(SSWPItems.DARK_OAK_STICK, "Dark Oak Stick");
			builder.add(SSWPItems.MANGROVE_STICK, "Mangrove Stick");
			builder.add(SSWPItems.CHERRY_STICK, "Cherry Stick");
			builder.add(SSWPItems.BAMBOO_STICK, "Bamboo Stick");
			builder.add(SSWPItems.CRIMSON_STICK, "Crimson Stick");
			builder.add(SSWPItems.WARPED_STICK, "Warped Stick");
			
			builder.add(SSWPCauldronGroups.GOLD.getTranslationKey(), "Gold");
			builder.add(SSWPCauldronGroups.NETHERITE.getTranslationKey(), "Netherite");
			builder.add(SSWPCauldronGroups.COPPER.getTranslationKey(), "Copper");
			builder.add(SSWPCauldronGroups.EXPOSED_COPPER.getTranslationKey(), "Exposed Copper");
			builder.add(SSWPCauldronGroups.WEATHERED_COPPER.getTranslationKey(), "Weathered Copper");
			builder.add(SSWPCauldronGroups.OXIDIZED_COPPER.getTranslationKey(), "Oxidized Copper");
			builder.add(SSWPCauldronGroups.WAXED_COPPER.getTranslationKey(), "Waxed Copper");
			builder.add(SSWPCauldronGroups.WAXED_EXPOSED_COPPER.getTranslationKey(), "Waxed Exposed Copper");
			builder.add(SSWPCauldronGroups.WAXED_WEATHERED_COPPER.getTranslationKey(), "Waxed Weathered Copper");
			builder.add(SSWPCauldronGroups.WAXED_OXIDIZED_COPPER.getTranslationKey(), "Waxed Oxidized Copper");
			
			builder.add(SSWPlus.MOD_ID + ".config", "Stairs Slabs Walls+ Options");
			builder.add(SSWPlus.MOD_ID + ".config.netherite_anvil.no_repair_cost_chance", "No Repair Cost Chance");
			builder.add(SSWPlus.MOD_ID + ".config.netherite_anvil.extra_damage", "Netherite Anvil Extra Damage");
			builder.add(SSWPlus.MOD_ID + ".config.netherite_anvil.no_repair_cost_chance.tooltip", "Chance for the Netherite Anvil to not increase the repair cost value of an item");
			builder.add(SSWPlus.MOD_ID + ".config.netherite_anvil.extra_damage.tooltip", "Extra damage from a falling Netherite Anvil");
			
			builder.add(SSWPTags.Blocks.OAK_SLABS, "Oak Slabs");
			builder.add(SSWPTags.Blocks.OAK_STAIRS, "Oak Stairs");
			builder.add(SSWPTags.Blocks.OAK_WALLS, "Oak Walls");
			builder.add(SSWPTags.Blocks.SPRUCE_SLABS, "Spruce Slabs");
			builder.add(SSWPTags.Blocks.SPRUCE_STAIRS, "Spruce Stairs");
			builder.add(SSWPTags.Blocks.SPRUCE_WALLS, "Spruce Walls");
			builder.add(SSWPTags.Blocks.BIRCH_SLABS, "Birch Slabs");
			builder.add(SSWPTags.Blocks.BIRCH_STAIRS, "Birch Stairs");
			builder.add(SSWPTags.Blocks.BIRCH_WALLS, "Birch Walls");
			builder.add(SSWPTags.Blocks.JUNGLE_SLABS, "Jungle Slabs");
			builder.add(SSWPTags.Blocks.JUNGLE_STAIRS, "Jungle Stairs");
			builder.add(SSWPTags.Blocks.JUNGLE_WALLS, "Jungle Walls");
			builder.add(SSWPTags.Blocks.ACACIA_SLABS, "Acacia Slabs");
			builder.add(SSWPTags.Blocks.ACACIA_STAIRS, "Acacia Stairs");
			builder.add(SSWPTags.Blocks.ACACIA_WALLS, "Acacia Walls");
			builder.add(SSWPTags.Blocks.DARK_OAK_SLABS, "Dark Oak Slabs");
			builder.add(SSWPTags.Blocks.DARK_OAK_STAIRS, "Dark Oak Stairs");
			builder.add(SSWPTags.Blocks.DARK_OAK_WALLS, "Dark Oak Walls");
			builder.add(SSWPTags.Blocks.MANGROVE_SLABS, "Mangrove Slabs");
			builder.add(SSWPTags.Blocks.MANGROVE_STAIRS, "Mangrove Stairs");
			builder.add(SSWPTags.Blocks.MANGROVE_WALLS, "Mangrove Walls");
			builder.add(SSWPTags.Blocks.CHERRY_SLABS, "Cherry Slabs");
			builder.add(SSWPTags.Blocks.CHERRY_STAIRS, "Cherry Stairs");
			builder.add(SSWPTags.Blocks.CHERRY_WALLS, "Cherry Walls");
			builder.add(SSWPTags.Blocks.BAMBOO_SLABS, "Bamboo Slabs");
			builder.add(SSWPTags.Blocks.BAMBOO_STAIRS, "Bamboo Stairs");
			builder.add(SSWPTags.Blocks.BAMBOO_WALLS, "Bamboo Walls");
			builder.add(SSWPTags.Blocks.CRIMSON_SLABS, "Crimson Slabs");
			builder.add(SSWPTags.Blocks.CRIMSON_STAIRS, "Crimson Stairs");
			builder.add(SSWPTags.Blocks.CRIMSON_WALLS, "Crimson Walls");
			builder.add(SSWPTags.Blocks.WARPED_SLABS, "Warped Slabs");
			builder.add(SSWPTags.Blocks.WARPED_STAIRS, "Warped Stairs");
			builder.add(SSWPTags.Blocks.WARPED_WALLS, "Warped Walls");
			
			builder.add(SSWPTags.Items.OAK_SLABS, "Oak Slabs");
			builder.add(SSWPTags.Items.OAK_STAIRS, "Oak Stairs");
			builder.add(SSWPTags.Items.OAK_WALLS, "Oak Walls");
			builder.add(SSWPTags.Items.SPRUCE_SLABS, "Spruce Slabs");
			builder.add(SSWPTags.Items.SPRUCE_STAIRS, "Spruce Stairs");
			builder.add(SSWPTags.Items.SPRUCE_WALLS, "Spruce Walls");
			builder.add(SSWPTags.Items.BIRCH_SLABS, "Birch Slabs");
			builder.add(SSWPTags.Items.BIRCH_STAIRS, "Birch Stairs");
			builder.add(SSWPTags.Items.BIRCH_WALLS, "Birch Walls");
			builder.add(SSWPTags.Items.JUNGLE_SLABS, "Jungle Slabs");
			builder.add(SSWPTags.Items.JUNGLE_STAIRS, "Jungle Stairs");
			builder.add(SSWPTags.Items.JUNGLE_WALLS, "Jungle Walls");
			builder.add(SSWPTags.Items.ACACIA_SLABS, "Acacia Slabs");
			builder.add(SSWPTags.Items.ACACIA_STAIRS, "Acacia Stairs");
			builder.add(SSWPTags.Items.ACACIA_WALLS, "Acacia Walls");
			builder.add(SSWPTags.Items.DARK_OAK_SLABS, "Dark Oak Slabs");
			builder.add(SSWPTags.Items.DARK_OAK_STAIRS, "Dark Oak Stairs");
			builder.add(SSWPTags.Items.DARK_OAK_WALLS, "Dark Oak Walls");
			builder.add(SSWPTags.Items.MANGROVE_SLABS, "Mangrove Slabs");
			builder.add(SSWPTags.Items.MANGROVE_STAIRS, "Mangrove Stairs");
			builder.add(SSWPTags.Items.MANGROVE_WALLS, "Mangrove Walls");
			builder.add(SSWPTags.Items.CHERRY_SLABS, "Cherry Slabs");
			builder.add(SSWPTags.Items.CHERRY_STAIRS, "Cherry Stairs");
			builder.add(SSWPTags.Items.CHERRY_WALLS, "Cherry Walls");
			builder.add(SSWPTags.Items.BAMBOO_SLABS, "Bamboo Slabs");
			builder.add(SSWPTags.Items.BAMBOO_STAIRS, "Bamboo Stairs");
			builder.add(SSWPTags.Items.BAMBOO_WALLS, "Bamboo Walls");
			builder.add(SSWPTags.Items.CRIMSON_SLABS, "Crimson Slabs");
			builder.add(SSWPTags.Items.CRIMSON_STAIRS, "Crimson Stairs");
			builder.add(SSWPTags.Items.CRIMSON_WALLS, "Crimson Walls");
			builder.add(SSWPTags.Items.WARPED_SLABS, "Warped Slabs");
			builder.add(SSWPTags.Items.WARPED_STAIRS, "Warped Stairs");
			builder.add(SSWPTags.Items.WARPED_WALLS, "Warped Walls");
		}
	}
	
	protected static final class CAEnglish extends FabricLanguageProvider {
		protected CAEnglish(FabricDataOutput dataOutput, CompletableFuture<WrapperLookup> registryLookup) {
			super(dataOutput, "en_ca", registryLookup);
		}
		
		@Override
		public void generateTranslations(WrapperLookup registryLookup, TranslationBuilder builder) {
			builder.add(SSWPBlocks.LIGHT_GRAY_WOOL_SLAB, "Light Grey Wool Slab");
			builder.add(SSWPBlocks.LIGHT_GRAY_WOOL_STAIRS, "Light Grey Wool Stairs");
			builder.add(SSWPBlocks.LIGHT_GRAY_WOOL_WALL, "Light Grey Wool Wall");
			builder.add(SSWPBlocks.GRAY_WOOL_SLAB, "Grey Wool Slab");
			builder.add(SSWPBlocks.GRAY_WOOL_STAIRS, "Grey Wool Stairs");
			builder.add(SSWPBlocks.GRAY_WOOL_WALL, "Grey Wool Wall");
			builder.add(SSWPBlocks.LIGHT_GRAY_TERRACOTTA_SLAB, "Light Grey Terracotta Slab");
			builder.add(SSWPBlocks.LIGHT_GRAY_TERRACOTTA_STAIRS, "Light Grey Terracotta Stairs");
			builder.add(SSWPBlocks.LIGHT_GRAY_TERRACOTTA_WALL, "Light Grey Terracotta Wall");
			builder.add(SSWPBlocks.GRAY_TERRACOTTA_SLAB, "Grey Terracotta Slab");
			builder.add(SSWPBlocks.GRAY_TERRACOTTA_STAIRS, "Grey Terracotta Stairs");
			builder.add(SSWPBlocks.GRAY_TERRACOTTA_WALL, "Grey Terracotta Wall");
			builder.add(SSWPBlocks.LIGHT_GRAY_CONCRETE_SLAB, "Light Grey Concrete Slab");
			builder.add(SSWPBlocks.LIGHT_GRAY_CONCRETE_STAIRS, "Light Grey Concrete Stairs");
			builder.add(SSWPBlocks.LIGHT_GRAY_CONCRETE_WALL, "Light Grey Concrete Wall");
			builder.add(SSWPBlocks.GRAY_CONCRETE_SLAB, "Grey Concrete Slab");
			builder.add(SSWPBlocks.GRAY_CONCRETE_STAIRS, "Grey Concrete Stairs");
			builder.add(SSWPBlocks.GRAY_CONCRETE_WALL, "Grey Concrete Wall");
			builder.add(SSWPBlocks.LIGHT_GRAY_STAINED_GLASS_SLAB, "Light Grey Stained Glass Slab");
			builder.add(SSWPBlocks.LIGHT_GRAY_STAINED_GLASS_STAIRS, "Light Grey Stained Glass Stairs");
			builder.add(SSWPBlocks.LIGHT_GRAY_STAINED_GLASS_WALL, "Light Grey Stained Glass Wall");
			builder.add(SSWPBlocks.GRAY_STAINED_GLASS_SLAB, "Grey Stained Glass Slab");
			builder.add(SSWPBlocks.GRAY_STAINED_GLASS_STAIRS, "Grey Stained Glass Stairs");
			builder.add(SSWPBlocks.GRAY_STAINED_GLASS_WALL, "Grey Stained Glass Wall");
		}
	}
}